- purl: pkg:golang/github.com/grafana/agent@0.21.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gv98-c6v1-aaaf
- purl: pkg:golang/github.com/grafana/agent@0.43.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-byrv-qe4s-yqfs
