- pkg:rpm/redhat/golang-github-prometheus-promu@0.15.0-15.1.gitd5383c5?arch=el8
- pkg:rpm/redhat/golang-github-prometheus-promu@0.15.0-15.2.gitd5383c5?arch=el9
- pkg:rpm/redhat/golang-github-prometheus-promu@0-1.git85ceabc?arch=el7
- pkg:rpm/redhat/golang-github-prometheus-promu@0-2.git85ceabc?arch=el7
- pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-2.git642a960?arch=el7
- pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-3.git642a960?arch=el7
- pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-3.git642a960?arch=el8
- pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-4.git642a960?arch=el8
- pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-5.git642a960?arch=el8
- pkg:rpm/redhat/golang-github-prometheus-promu@0-5.git85ceabc?arch=el7
