- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.15.0-15.1.gitd5383c5?arch=el8
  affected_by_vulnerabilities:
    - VCID-aafc-9fsp-aaam
    - VCID-q2tw-bu8w-aaah
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.15.0-15.2.gitd5383c5?arch=el9
  affected_by_vulnerabilities:
    - VCID-eys9-8vhk-aaaa
    - VCID-px9q-79aq-aaah
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0-1.git85ceabc?arch=el7
  affected_by_vulnerabilities:
    - VCID-8g31-3v68-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0-2.git85ceabc?arch=el7
  affected_by_vulnerabilities:
    - VCID-3qb1-f6fw-aaad
    - VCID-kac9-8rqu-aaaa
    - VCID-sb3k-9d77-aaab
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-2.git642a960?arch=el7
  affected_by_vulnerabilities:
    - VCID-3gua-vux5-aaaq
    - VCID-6ypc-78mx-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-3.git642a960?arch=el8
  affected_by_vulnerabilities:
    - VCID-8dup-t5n7-aaas
    - VCID-ad6a-7pdt-aaaf
    - VCID-uwa2-eyvn-aaaj
    - VCID-zxgs-3w22-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-3.git642a960?arch=el7
  affected_by_vulnerabilities:
    - VCID-ad6a-7pdt-aaaf
    - VCID-zxgs-3w22-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-4.git642a960?arch=el8
  affected_by_vulnerabilities:
    - VCID-b1t1-32t4-aaaf
    - VCID-gfdc-2q2q-aaak
    - VCID-mtfq-ngz6-aaad
    - VCID-qggy-g6kz-aaaj
    - VCID-tdq5-pwwt-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-5.git642a960?arch=el8
  affected_by_vulnerabilities:
    - VCID-pz2t-umsf-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0-5.git85ceabc?arch=el7
  affected_by_vulnerabilities:
    - VCID-3gua-vux5-aaaq
    - VCID-6ypc-78mx-aaac
    - VCID-9uwj-8vtu-aaab
  fixing_vulnerabilities: []
