- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.0
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.1
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.2
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.11
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.21.6
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.22.0
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.25.4.1
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.26.0
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.26.5
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.0
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.1
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.3
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.4
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.7.0
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.7.1
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.8
- pkg:maven/org.csanchez.jenkins.plugins/kubernetes@3910.ve59cec5e33ea
