- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.0
  affected_by_vulnerabilities:
    - VCID-pxs4-dubj-aaar
  fixing_vulnerabilities: []
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.1
  affected_by_vulnerabilities:
    - VCID-tqhb-44tk-aaap
  fixing_vulnerabilities:
    - VCID-pxs4-dubj-aaar
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tqhb-44tk-aaap
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tqhb-44tk-aaap
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.21.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
    - VCID-tvn2-t2c2-aaaa
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.22.0
  affected_by_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
    - VCID-tvn2-t2c2-aaaa
  fixing_vulnerabilities: []
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.25.4.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
    - VCID-tvn2-t2c2-aaaa
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.26.0
  affected_by_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
    - VCID-tvn2-t2c2-aaaa
  fixing_vulnerabilities: []
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.26.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
    - VCID-tvn2-t2c2-aaaa
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.0
  affected_by_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
  fixing_vulnerabilities: []
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.1
  affected_by_vulnerabilities:
    - VCID-tvn2-t2c2-aaaa
  fixing_vulnerabilities: []
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.3
  affected_by_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
    - VCID-tvn2-t2c2-aaaa
  fixing_vulnerabilities: []
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-df2s-d47m-aaar
    - VCID-stbc-apza-aaaa
    - VCID-tvn2-t2c2-aaaa
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.7.0
  affected_by_vulnerabilities:
    - VCID-nhu6-v2bj-aaaa
  fixing_vulnerabilities: []
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.7.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nhu6-v2bj-aaaa
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nhu6-v2bj-aaaa
- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@3910.ve59cec5e33ea
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7end-fegr-aaac
