- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=x86&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=riscv64&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=s390x&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=x86_64&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=aarch64&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=armhf&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=armv7&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.30.9-r0?arch=ppc64le&distroversion=v3.20&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=armhf&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=armv7&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=loongarch64&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=ppc64le&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=riscv64&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=x86_64&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=aarch64&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=s390x&distroversion=v3.21&reponame=community
- pkg:apk/alpine/kubernetes@1.31.5-r0?arch=x86&distroversion=v3.21&reponame=community
