- purl: pkg:golang/k8s.io/kubernetes/cmd/kubelet@1.13.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-yprx-a2k8-aaap
- purl: pkg:golang/k8s.io/kubernetes/cmd/kubelet@1.14.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-yprx-a2k8-aaap
