- purl: pkg:npm/docker-compose-remote-api@0.1.1
  affected_by_vulnerabilities:
    - VCID-faey-4q72-aaar
  fixing_vulnerabilities: []
- purl: pkg:npm/docker-compose-remote-api@0.1.2
  affected_by_vulnerabilities:
    - VCID-faey-4q72-aaar
  fixing_vulnerabilities: []
- purl: pkg:npm/docker-compose-remote-api@0.1.3
  affected_by_vulnerabilities:
    - VCID-faey-4q72-aaar
  fixing_vulnerabilities: []
- purl: pkg:npm/docker-compose-remote-api@0.1.4
  affected_by_vulnerabilities:
    - VCID-faey-4q72-aaar
  fixing_vulnerabilities: []
