- purl: pkg:ebuild/app-containers/docker@25.0.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2pf3-c2mj-aaac
    - VCID-3aaq-ny82-aaag
    - VCID-98m9-ft46-aaah
    - VCID-axr6-brgf-aaas
    - VCID-d9b3-cf4c-aaaj
    - VCID-ghmn-wkwj-aaam
    - VCID-h7tv-gsrm-aaab
    - VCID-jbdq-mdbt-aaap
    - VCID-jnm2-7vwf-aaaj
    - VCID-qbd4-zhx2-aaap
    - VCID-qgrb-pu21-aaab
    - VCID-t2wk-4hj9-aaad
    - VCID-vnpd-ha1h-aaab
