- purl: pkg:rpm/redhat/rhc-worker-playbook@0.1.10-1?arch=el9_5
  affected_by_vulnerabilities:
    - VCID-3mm8-6kkz-aaaj
    - VCID-jwn5-5rse-aaah
    - VCID-mg48-8mnh-aaaa
    - VCID-u245-peha-aaag
  fixing_vulnerabilities: []
