- purl: pkg:rpm/redhat/prometheus-webhook-snmp@container-1.3?arch=0-13
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-webhook-snmp@container-1.3?arch=0-14
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
  fixing_vulnerabilities: []
