- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-6?arch=el8
  affected_by_vulnerabilities:
    - VCID-rg13-zrka-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-8?arch=el8_6
  affected_by_vulnerabilities:
    - VCID-ah3h-rgmk-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-9?arch=el8_7
  affected_by_vulnerabilities:
    - VCID-rxj4-rqm2-aaaf
  fixing_vulnerabilities: []
