- pkg:deb/ubuntu/ansible@1.1%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.1%2Bdfsg-1~ubuntu12.04.1
- pkg:deb/ubuntu/ansible@1.1%2Bdfsg-1~ubuntu12.10.1
- pkg:deb/ubuntu/ansible@1.1%2Bdfsg-1~ubuntu13.04.1
- pkg:deb/ubuntu/ansible@1.3.4%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.4.0%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.4.1%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.4.3%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.4.3%2Bdfsg-1~ubuntu13.10.1
- pkg:deb/ubuntu/ansible@1.4.4%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.4.4%2Bdfsg-1~ubuntu12.04.1
- pkg:deb/ubuntu/ansible@1.4.4%2Bdfsg-1~ubuntu12.10.1
- pkg:deb/ubuntu/ansible@1.4.4%2Bdfsg-1~ubuntu13.04.1
- pkg:deb/ubuntu/ansible@1.4.4%2Bdfsg-1~ubuntu13.10.1
- pkg:deb/ubuntu/ansible@1.5.4%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.5.5%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.10%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.10%2Bdfsg-1~ubuntu14.04.1
- pkg:deb/ubuntu/ansible@1.6.1%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.2%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.3%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.5%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.6%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.6%2Bdfsg-1~ubuntu14.04.1
- pkg:deb/ubuntu/ansible@1.6.8%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.8%2Bdfsg-1~ubuntu14.04.1
- pkg:deb/ubuntu/ansible@1.6.9%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.6.9%2Bdfsg-1~ubuntu14.04.1
- pkg:deb/ubuntu/ansible@1.7.1%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.7.1%2Bdfsg-1~ubuntu14.04.1
- pkg:deb/ubuntu/ansible@1.7.2%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.7.2%2Bdfsg-1~ubuntu14.04.1
- pkg:deb/ubuntu/ansible@1.7.2%2Bdfsg-2
- pkg:deb/ubuntu/ansible@1.9.2%2Bdfsg-1
- pkg:deb/ubuntu/ansible@1.9.2%2Bdfsg-2
- pkg:deb/ubuntu/ansible@1.9.4-1
- pkg:deb/ubuntu/ansible@2.0.0.2-2
- pkg:deb/ubuntu/ansible@2.0.0.2-2ubuntu1
- pkg:deb/ubuntu/ansible@2.0.0.2-2ubuntu1.1
- pkg:deb/ubuntu/ansible@2.0.0.2-2ubuntu1.2
- pkg:deb/ubuntu/ansible@2.0.0.2-2ubuntu1.3
- pkg:deb/ubuntu/ansible@2.0.2.0-1
- pkg:deb/ubuntu/ansible@2.1.0.0-1
- pkg:deb/ubuntu/ansible@2.1.1.0-1
- pkg:deb/ubuntu/ansible@2.1.1.0-1~ubuntu16.04.1
- pkg:deb/ubuntu/ansible@2.2.0.0-1
- pkg:deb/ubuntu/ansible@2.2.0.0-2
- pkg:deb/ubuntu/ansible@2.2.0.0-3
- pkg:deb/ubuntu/ansible@2.2.0.0-4
- pkg:deb/ubuntu/ansible@2.2.1.0-1
- pkg:deb/ubuntu/ansible@2.2.1.0-2
- pkg:deb/ubuntu/ansible@2.3.1.0%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.3.1.0%2Bdfsg-2
- pkg:deb/ubuntu/ansible@2.4.0.0%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.4.2.0%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.4.3.0%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.5.0%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.5.1%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.5.1%2Bdfsg-1ubuntu0.1
- pkg:deb/ubuntu/ansible@2.5.2%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.5.2%2Bdfsg-2
- pkg:deb/ubuntu/ansible@2.5.3%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.5.3%2Bdfsg-2
- pkg:deb/ubuntu/ansible@2.5.5%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.6.1%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.6.3%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.6.4%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.6.5%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.7.1%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.7.1%2Bdfsg-2
- pkg:deb/ubuntu/ansible@2.7.1%2Bdfsg-2ubuntu1
- pkg:deb/ubuntu/ansible@2.7.1%2Bdfsg-2ubuntu2
- pkg:deb/ubuntu/ansible@2.7.5%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.7.6%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.7.7%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.7.8%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.7.8%2Bdfsg-1ubuntu0.19.04.1
- pkg:deb/ubuntu/ansible@2.7.8%2Bdfsg-1ubuntu1
- pkg:deb/ubuntu/ansible@2.8.3%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.8.6%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.9.2%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.9.4%2Bdfsg-1
- pkg:deb/ubuntu/ansible@2.9.6%2Bdfsg-1
