- purl: pkg:rpm/redhat/ansible@2.2.0.0-1?arch=el7
  affected_by_vulnerabilities:
    - VCID-czq6-67wz-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.2.1.0-1?arch=el7
  affected_by_vulnerabilities:
    - VCID-scu2-mz1c-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.2.1.0-2?arch=el7
  affected_by_vulnerabilities:
    - VCID-6nh4-7nf5-aaad
    - VCID-scu2-mz1c-aaan
    - VCID-xmhy-jf4y-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.2.3.0-1?arch=el7
  affected_by_vulnerabilities:
    - VCID-9e5w-5m3m-aaaj
    - VCID-bdvq-5546-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.3.0.0-1?arch=el7
  affected_by_vulnerabilities:
    - VCID-a5xy-6pjt-aaah
    - VCID-u9vm-ngpz-aaas
    - VCID-v274-wy4s-aaaq
    - VCID-yusr-p2mm-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.3.0.0-4?arch=el7
  affected_by_vulnerabilities:
    - VCID-bdvq-5546-aaap
    - VCID-q52e-x2mz-aaaa
    - VCID-scu2-mz1c-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.3.1.0-3?arch=el7
  affected_by_vulnerabilities:
    - VCID-9e5w-5m3m-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.3.2.0-2?arch=el7
  affected_by_vulnerabilities:
    - VCID-8g31-3v68-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.4.0.0-5?arch=el7
  affected_by_vulnerabilities:
    - VCID-vhdj-z1ew-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.4.3.0-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-1b26-n9vn-aaab
    - VCID-qez8-dgmj-aaak
    - VCID-xmx5-a45m-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.4.4.0-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-4tkc-jaj1-aaam
    - VCID-m6ju-nbce-aaag
    - VCID-zx4q-ry22-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.4.5.0-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-vpzy-gc78-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.4.6.0-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-px3x-t4ay-aaaa
    - VCID-vpzy-gc78-aaag
    - VCID-yxyq-9868-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.5.11-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-4256-s7ta-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.5.13-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-56gr-ex7m-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.5.14-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-2989-kmjf-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.5.15-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-66z9-6ea3-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.5.5-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-vpzy-gc78-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.5.6-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-px3x-t4ay-aaaa
    - VCID-yxyq-9868-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.10-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-56gr-ex7m-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.1-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-px3x-t4ay-aaaa
    - VCID-yxyq-9868-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.11-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-2989-kmjf-aaas
    - VCID-4256-s7ta-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.14-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-66z9-6ea3-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.18-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-qy3t-m3jq-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.19-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-4tsx-tb15-aaar
    - VCID-66z9-6ea3-aaaf
    - VCID-qy3t-m3jq-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.20-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-uchf-z1us-aaaj
    - VCID-ucre-31md-aaad
    - VCID-zk4f-r19r-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.6.7-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-4256-s7ta-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.1-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-4256-s7ta-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.12-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-qy3t-m3jq-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.13-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-4tsx-tb15-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.14-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-uchf-z1us-aaaj
    - VCID-ucre-31md-aaad
    - VCID-zk4f-r19r-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.15-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-m1j9-6xnm-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.16-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-1puc-u4y9-aaap
    - VCID-wkkk-5njy-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.17-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-9xje-8wsd-aaam
    - VCID-dp5x-5n9f-aaah
    - VCID-emd7-stwr-aaan
    - VCID-mrhc-f3xq-aaaa
    - VCID-nqsx-thdv-aaac
    - VCID-nxj9-2mgr-aaak
    - VCID-t2tw-36t9-aaab
    - VCID-x97v-vpy8-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.18-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-sxyq-umyp-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.4-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-56gr-ex7m-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.5-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-2989-kmjf-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.7.8-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-66z9-6ea3-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.11-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-9xje-8wsd-aaam
    - VCID-dp5x-5n9f-aaah
    - VCID-emd7-stwr-aaan
    - VCID-mrhc-f3xq-aaaa
    - VCID-nqsx-thdv-aaac
    - VCID-nxj9-2mgr-aaak
    - VCID-t2tw-36t9-aaab
    - VCID-x97v-vpy8-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.11-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-9xje-8wsd-aaam
    - VCID-dp5x-5n9f-aaah
    - VCID-emd7-stwr-aaan
    - VCID-mrhc-f3xq-aaaa
    - VCID-nqsx-thdv-aaac
    - VCID-nxj9-2mgr-aaak
    - VCID-t2tw-36t9-aaab
    - VCID-x97v-vpy8-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.15-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-na52-qryf-aaae
    - VCID-pgrs-n6fm-aaam
    - VCID-r43q-bz4b-aaah
    - VCID-z25c-x91u-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.15-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-na52-qryf-aaae
    - VCID-pgrs-n6fm-aaam
    - VCID-r43q-bz4b-aaah
    - VCID-z25c-x91u-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.16-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-sxyq-umyp-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.16-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-sxyq-umyp-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.2-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-qy3t-m3jq-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.2-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-qy3t-m3jq-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.4-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-3tap-8hpn-aaad
    - VCID-4tsx-tb15-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.4-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-3tap-8hpn-aaad
    - VCID-4tsx-tb15-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.6-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-uchf-z1us-aaaj
    - VCID-ucre-31md-aaad
    - VCID-zk4f-r19r-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.6-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-uchf-z1us-aaaj
    - VCID-ucre-31md-aaad
    - VCID-zk4f-r19r-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.7-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-m1j9-6xnm-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.7-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-m1j9-6xnm-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.8-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-1puc-u4y9-aaap
    - VCID-wkkk-5njy-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.8.8-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-1puc-u4y9-aaap
    - VCID-wkkk-5njy-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.1-1?arch=el8
  affected_by_vulnerabilities:
    - VCID-m1j9-6xnm-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.1-1?arch=el7
  affected_by_vulnerabilities:
    - VCID-m1j9-6xnm-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.13-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-z25c-x91u-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.13-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-z25c-x91u-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.18-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
    - VCID-hx4y-7eby-aaad
    - VCID-qz75-v9j5-aaaa
    - VCID-qzhf-2cvf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.18-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
    - VCID-hx4y-7eby-aaad
    - VCID-qz75-v9j5-aaaa
    - VCID-qzhf-2cvf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.20-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-ugk3-fc38-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.20-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-ugk3-fc38-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.21-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-ugk3-fc38-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.23-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-xhtk-kssv-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.23-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-xhtk-kssv-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.23-1?arch=el8ap
  affected_by_vulnerabilities:
    - VCID-xhtk-kssv-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.27-1?arch=el8ap
  affected_by_vulnerabilities:
    - VCID-2zwd-cb9n-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.27-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-2zwd-cb9n-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.27-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-2zwd-cb9n-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.4-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-1puc-u4y9-aaap
    - VCID-wkkk-5njy-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.4-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-1puc-u4y9-aaap
    - VCID-wkkk-5njy-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.6-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-yxbw-377b-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.6-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-yxbw-377b-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.7-1?arch=el8ae
  affected_by_vulnerabilities:
    - VCID-9xje-8wsd-aaam
    - VCID-dp5x-5n9f-aaah
    - VCID-emd7-stwr-aaan
    - VCID-mrhc-f3xq-aaaa
    - VCID-nqsx-thdv-aaac
    - VCID-nxj9-2mgr-aaak
    - VCID-qxat-hky3-aaab
    - VCID-sxyq-umyp-aaar
    - VCID-t2tw-36t9-aaab
    - VCID-x97v-vpy8-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/ansible@2.9.7-1?arch=el7ae
  affected_by_vulnerabilities:
    - VCID-9xje-8wsd-aaam
    - VCID-dp5x-5n9f-aaah
    - VCID-emd7-stwr-aaan
    - VCID-mrhc-f3xq-aaaa
    - VCID-nqsx-thdv-aaac
    - VCID-nxj9-2mgr-aaak
    - VCID-qxat-hky3-aaab
    - VCID-sxyq-umyp-aaar
    - VCID-t2tw-36t9-aaab
    - VCID-x97v-vpy8-aaan
  fixing_vulnerabilities: []
