- purl: pkg:alpine/ansible@2.10.1-r0?arch=aarch64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r7zs-rzfz-aaap
- purl: pkg:alpine/ansible@2.10.1-r0?arch=armhf&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r7zs-rzfz-aaap
- purl: pkg:alpine/ansible@2.10.1-r0?arch=armv7&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r7zs-rzfz-aaap
- purl: pkg:alpine/ansible@2.10.1-r0?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r7zs-rzfz-aaap
- purl: pkg:alpine/ansible@2.10.1-r0?arch=s390x&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r7zs-rzfz-aaap
- purl: pkg:alpine/ansible@2.10.1-r0?arch=x86&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r7zs-rzfz-aaap
- purl: pkg:alpine/ansible@2.10.1-r0?arch=x86_64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r7zs-rzfz-aaap
- purl: pkg:alpine/ansible@2.10.7-r0?arch=armv7&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
- purl: pkg:alpine/ansible@2.10.7-r0?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
- purl: pkg:alpine/ansible@2.10.7-r0?arch=s390x&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
- purl: pkg:alpine/ansible@2.10.7-r0?arch=x86&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
- purl: pkg:alpine/ansible@2.10.7-r0?arch=x86_64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
- purl: pkg:alpine/ansible@2.10.7-r0?arch=aarch64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
- purl: pkg:alpine/ansible@2.10.7-r0?arch=armhf&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
