- pkg:golang/github.com/kubernetes/kubernetes@1.10.11
- pkg:golang/github.com/kubernetes/kubernetes@1.1.1
- pkg:golang/github.com/kubernetes/kubernetes@1.11.5
- pkg:golang/github.com/kubernetes/kubernetes@1.12.3
- pkg:golang/github.com/kubernetes/kubernetes@1.17.13
- pkg:golang/github.com/kubernetes/kubernetes@1.18.10
- pkg:golang/github.com/kubernetes/kubernetes@1.19.3
- pkg:golang/github.com/kubernetes/kubernetes@1.2.0
- pkg:golang/github.com/kubernetes/kubernetes@1.2.0-alpha.6
- pkg:golang/github.com/kubernetes/kubernetes@1.22.16
- pkg:golang/github.com/kubernetes/kubernetes@1.23.14
- pkg:golang/github.com/kubernetes/kubernetes@1.24.8
- pkg:golang/github.com/kubernetes/kubernetes@1.25.4
