- purl: pkg:golang/github.com/kubernetes/kubernetes@1.10.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-e1j4-7hm1-aaam
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.1.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3guf-r76t-aaar
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.11.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-e1j4-7hm1-aaam
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.12.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-e1j4-7hm1-aaam
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.17.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1y4g-d4ck-aaaq
    - VCID-c4gh-vs6u-aaaj
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.18.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1y4g-d4ck-aaaq
    - VCID-c4gh-vs6u-aaaj
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.19.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1y4g-d4ck-aaaq
    - VCID-4qay-qj2b-aaag
    - VCID-c4gh-vs6u-aaaj
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.2.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fr94-mwxc-aaac
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.2.0-alpha.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-4f3q-g2t9-aaab
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.22.16
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-48p6-mp24-aaac
    - VCID-pc4t-u14n-aaae
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.23.14
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-48p6-mp24-aaac
    - VCID-pc4t-u14n-aaae
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.24.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-48p6-mp24-aaac
    - VCID-pc4t-u14n-aaae
- purl: pkg:golang/github.com/kubernetes/kubernetes@1.25.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-48p6-mp24-aaac
    - VCID-pc4t-u14n-aaae
