- purl: pkg:rpm/redhat/grafana@10.2.6-4?arch=el9
  affected_by_vulnerabilities:
    - VCID-h2kc-9hcv-aaap
    - VCID-kewv-1ncx-aaar
    - VCID-mw4h-kyun-aaag
    - VCID-qtfg-fbmr-aaaq
    - VCID-qxwq-ayc1-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@10.2.6-7?arch=el9_5
  affected_by_vulnerabilities:
    - VCID-pepv-ks55-9yg1
    - VCID-vk2s-wc8t-sqhh
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@10.2.6-9?arch=el9_5
  affected_by_vulnerabilities:
    - VCID-qbvf-4rp6-gbcu
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@4.3.2-4?arch=el7cp
  affected_by_vulnerabilities:
    - VCID-ejyn-tdpk-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@4.6.4-1?arch=el7rhgs
  affected_by_vulnerabilities:
    - VCID-74f2-vsqc-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@5.2.4-1?arch=el7cp
  affected_by_vulnerabilities:
    - VCID-74f2-vsqc-aaaa
    - VCID-ws3t-kfkn-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@5.2.4-2?arch=el7cp
  affected_by_vulnerabilities:
    - VCID-ejyn-tdpk-aaaj
    - VCID-tdv4-ytwv-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@5.2.4-3?arch=el7cp
  affected_by_vulnerabilities:
    - VCID-3ump-wuym-aaag
    - VCID-7sn5-sxp2-aaar
    - VCID-gbsq-myef-aaaa
    - VCID-td78-zefu-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@5.2.4-3?arch=el7rhgs
  affected_by_vulnerabilities:
    - VCID-gbsq-myef-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@5.2.4-5?arch=el7rhgs
  affected_by_vulnerabilities:
    - VCID-nk3v-tvmw-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@5.2.4-6?arch=el7rhgs
  affected_by_vulnerabilities:
    - VCID-86a4-948a-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.2.2-6?arch=el8_1
  affected_by_vulnerabilities:
    - VCID-gbsq-myef-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.2.2-7?arch=el8_1
  affected_by_vulnerabilities:
    - VCID-hwv4-qssy-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.2.2-9?arch=el8_1
  affected_by_vulnerabilities:
    - VCID-f9d5-f658-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.3.6-1?arch=el8
  affected_by_vulnerabilities:
    - VCID-b6sq-gy55-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.3.6-2?arch=el8_2
  affected_by_vulnerabilities:
    - VCID-gbsq-myef-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.3.6-3?arch=el8_2
  affected_by_vulnerabilities:
    - VCID-hwv4-qssy-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.3.6-5?arch=el8_2
  affected_by_vulnerabilities:
    - VCID-f9d5-f658-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.3.6-6?arch=el8_2
  affected_by_vulnerabilities:
    - VCID-u5bp-tavb-2uaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@6.7.4-3?arch=el8
  affected_by_vulnerabilities:
    - VCID-1yv9-mqca-aaah
    - VCID-3r9x-k37c-aaaf
    - VCID-4jwf-ed3r-aaas
    - VCID-c6rp-37xf-aaaq
    - VCID-g3cu-aj54-aaar
    - VCID-g87y-96rb-aaaf
    - VCID-smny-jjyv-aaag
    - VCID-vn5a-c4pk-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.3.6-2?arch=el8
  affected_by_vulnerabilities:
    - VCID-frr5-mkd6-aaaq
    - VCID-zcrr-8r4t-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.3.6-3?arch=el8_4
  affected_by_vulnerabilities:
    - VCID-hwv4-qssy-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.3.6-4?arch=el8_4
  affected_by_vulnerabilities:
    - VCID-nk3v-tvmw-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.3.6-5?arch=el8_4
  affected_by_vulnerabilities:
    - VCID-f9d5-f658-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.3.6-6?arch=el8_4
  affected_by_vulnerabilities:
    - VCID-6y3x-kyj7-aaaf
    - VCID-te2m-j4fe-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.3.6-7?arch=el8_4
  affected_by_vulnerabilities:
    - VCID-3syk-cter-xyde
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.3.6-8?arch=el8_4
  affected_by_vulnerabilities:
    - VCID-u5bp-tavb-2uaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.11-2?arch=el8
  affected_by_vulnerabilities:
    - VCID-bhfv-khhr-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.11-3?arch=el8_6
  affected_by_vulnerabilities:
    - VCID-f9d5-f658-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.11-4?arch=el8_6
  affected_by_vulnerabilities:
    - VCID-6y3x-kyj7-aaaf
    - VCID-te2m-j4fe-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.11-5?arch=el9_0
  affected_by_vulnerabilities:
    - VCID-f9d5-f658-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.11-6?arch=el9_0
  affected_by_vulnerabilities:
    - VCID-6y3x-kyj7-aaaf
    - VCID-te2m-j4fe-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.11-7?arch=el9_0
  affected_by_vulnerabilities:
    - VCID-vk2s-wc8t-sqhh
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.15-3?arch=el9
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
    - VCID-4jac-1s1e-aaag
    - VCID-6vwn-qdd6-aaab
    - VCID-7jyw-7cbe-aaag
    - VCID-8fm5-p9ys-aaag
    - VCID-b8kc-15j6-aaan
    - VCID-cn47-xzgw-aaas
    - VCID-f55p-mnpt-aaan
    - VCID-f5nz-63tm-aaan
    - VCID-ftf6-7n4e-aaaf
    - VCID-ndaw-bvc2-aaaq
    - VCID-nq47-th3r-aaaj
    - VCID-qkhh-p4bq-aaar
    - VCID-trc1-jwfd-aaaa
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.15-3?arch=el8
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
    - VCID-4jac-1s1e-aaag
    - VCID-6vwn-qdd6-aaab
    - VCID-7jyw-7cbe-aaag
    - VCID-8fm5-p9ys-aaag
    - VCID-b8kc-15j6-aaan
    - VCID-cn47-xzgw-aaas
    - VCID-f55p-mnpt-aaan
    - VCID-f5nz-63tm-aaan
    - VCID-ftf6-7n4e-aaaf
    - VCID-ndaw-bvc2-aaaq
    - VCID-nq47-th3r-aaaj
    - VCID-qkhh-p4bq-aaar
    - VCID-trc1-jwfd-aaaa
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.15-4?arch=el8
  affected_by_vulnerabilities:
    - VCID-1s79-uech-aaak
    - VCID-24ms-6tr4-aaas
    - VCID-ak74-bz7v-aaab
    - VCID-xywa-ra13-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.15-5?arch=el8_8
  affected_by_vulnerabilities:
    - VCID-6y3x-kyj7-aaaf
    - VCID-te2m-j4fe-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.9-4?arch=el8
  affected_by_vulnerabilities:
    - VCID-8dup-t5n7-aaas
    - VCID-b1t1-32t4-aaaf
    - VCID-f8jk-rt36-aaaj
    - VCID-gfdc-2q2q-aaak
    - VCID-tdq5-pwwt-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@7.5.9-5?arch=el8_5
  affected_by_vulnerabilities:
    - VCID-nk3v-tvmw-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.0.9-2?arch=el9
  affected_by_vulnerabilities:
    - VCID-1s79-uech-aaak
    - VCID-24ms-6tr4-aaas
    - VCID-ak74-bz7v-aaab
    - VCID-u48c-9ys3-aaas
    - VCID-xywa-ra13-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.0.9-3?arch=el9_2
  affected_by_vulnerabilities:
    - VCID-gya3-7evs-aaaq
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.0.9-4?arch=el9_2
  affected_by_vulnerabilities:
    - VCID-6y3x-kyj7-aaaf
    - VCID-te2m-j4fe-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.0.9-5?arch=el9_2
  affected_by_vulnerabilities:
    - VCID-vk2s-wc8t-sqhh
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.0.9-6?arch=el9_2
  affected_by_vulnerabilities:
    - VCID-qbvf-4rp6-gbcu
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-16?arch=el9_4
  affected_by_vulnerabilities:
    - VCID-9g94-13dw-aaaf
    - VCID-w9eb-4e2m-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-16?arch=el8_10
  affected_by_vulnerabilities:
    - VCID-9g94-13dw-aaaf
    - VCID-w9eb-4e2m-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-17?arch=el8_10
  affected_by_vulnerabilities:
    - VCID-h2kc-9hcv-aaap
    - VCID-qtfg-fbmr-aaaq
    - VCID-qxwq-ayc1-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-17?arch=el9_4
  affected_by_vulnerabilities:
    - VCID-vk2s-wc8t-sqhh
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-18?arch=el8_10
  affected_by_vulnerabilities:
    - VCID-kewv-1ncx-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-19?arch=el9_4
  affected_by_vulnerabilities:
    - VCID-73xn-apdp-r3fe
    - VCID-pepv-ks55-9yg1
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-20?arch=el8_10
  affected_by_vulnerabilities:
    - VCID-73xn-apdp-r3fe
    - VCID-pepv-ks55-9yg1
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-21?arch=el9_4
  affected_by_vulnerabilities:
    - VCID-sxrd-1917-xffg
    - VCID-vsr4-mgce-mfew
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-21?arch=el8_10
  affected_by_vulnerabilities:
    - VCID-sxrd-1917-xffg
    - VCID-vsr4-mgce-mfew
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-22?arch=el9_4
  affected_by_vulnerabilities:
    - VCID-qbvf-4rp6-gbcu
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-7?arch=el9_3
  affected_by_vulnerabilities:
    - VCID-bde1-3cj5-aaan
    - VCID-cqex-t7k3-aaaq
    - VCID-drkd-6ygy-aaaj
    - VCID-heua-x4ft-aaaa
    - VCID-jbdq-mdbt-aaap
    - VCID-kpga-3c6n-aaaj
    - VCID-p3gm-x8ng-aaan
    - VCID-yswm-fu1v-aaac
    - VCID-zzee-2a7m-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-7?arch=el8_9
  affected_by_vulnerabilities:
    - VCID-gya3-7evs-aaaq
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-8?arch=el9_3
  affected_by_vulnerabilities:
    - VCID-9g94-13dw-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@9.2.10-8?arch=el8_9
  affected_by_vulnerabilities:
    - VCID-9g94-13dw-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@container-v3.11?arch=141-2
  affected_by_vulnerabilities:
    - VCID-qbz3-r843-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@container-v3.11?arch=146-2
  affected_by_vulnerabilities:
    - VCID-3vky-ea2p-aaap
    - VCID-6ap7-zs9m-aaag
    - VCID-hvu5-f1bj-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@container-v3.11?arch=82-3
  affected_by_vulnerabilities:
    - VCID-x3hr-wgvd-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@container-v3.11?arch=98-7
  affected_by_vulnerabilities:
    - VCID-r5q6-db7e-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@container-v4.1?arch=14-201908291507
  affected_by_vulnerabilities:
    - VCID-3gua-vux5-aaaq
    - VCID-6ypc-78mx-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@container-v4.3?arch=2-202002112006
  affected_by_vulnerabilities:
    - VCID-e1wn-9ha4-aaah
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/grafana@container-v4.3?arch=0-202001211731
  affected_by_vulnerabilities:
    - VCID-kq1v-8r3r-aaaf
  fixing_vulnerabilities: []
