- purl: pkg:golang/github.com/traefik/traefik/v3@3.0.0-beta5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-23u4-hqwe-aaam
    - VCID-rsgp-hexa-aaar
    - VCID-yyu2-j1eg-aaaq
- purl: pkg:golang/github.com/traefik/traefik/v3@3.0.0-rc5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-j7j5-t234-aaad
    - VCID-vqv3-5g7z-aaaj
- purl: pkg:golang/github.com/traefik/traefik/v3@3.0.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7z6n-qpw7-aaad
- purl: pkg:golang/github.com/traefik/traefik/v3@3.0.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jz9b-xau1-aaak
- purl: pkg:golang/github.com/traefik/traefik/v3@3.0.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r5m8-st86-aaap
- purl: pkg:golang/github.com/traefik/traefik/v3@3.0.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrdg-musw-aaad
- purl: pkg:golang/github.com/traefik/traefik/v3@3.1.0-rc3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrdg-musw-aaad
- purl: pkg:golang/github.com/traefik/traefik/v3@3.1.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-g4ue-jpuh-efcu
- purl: pkg:golang/github.com/traefik/traefik/v3@3.2.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ytds-yy67-9kg9
- purl: pkg:golang/github.com/traefik/traefik/v3@3.2.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-m3wf-4kh2-jfh2
- purl: pkg:golang/github.com/traefik/traefik/v3@3.3.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-6718-3gp5-jbh8
    - VCID-7vtf-2p25-57h2
    - VCID-f2j2-5199-r7e9
- purl: pkg:golang/github.com/traefik/traefik/v3@3.4.0-rc1
  affected_by_vulnerabilities:
    - VCID-6718-3gp5-jbh8
    - VCID-7vtf-2p25-57h2
    - VCID-f2j2-5199-r7e9
  fixing_vulnerabilities: []
- purl: pkg:golang/github.com/traefik/traefik/v3@3.4.0-rc2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-6718-3gp5-jbh8
    - VCID-7vtf-2p25-57h2
    - VCID-f2j2-5199-r7e9
- purl: pkg:golang/github.com/traefik/traefik/v3@3.4.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-866c-a24w-wyfu
- purl: pkg:golang/github.com/traefik/traefik/v3@3.4.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hpgu-na1u-b7ae
- purl: pkg:golang/github.com/traefik/traefik/v3@3.5.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hpgu-na1u-b7ae
- purl: pkg:golang/github.com/traefik/traefik/v3@3.6.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-g6hx-vsar-dqew
    - VCID-ukj8-apgc-n7hp
