- purl: pkg:golang/github.com/docker/docker@1.0.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2dtu-g7wf-aaak
- purl: pkg:golang/github.com/docker/docker@1.3.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q2y6-4n1b-aaae
- purl: pkg:golang/github.com/docker/docker@1.3.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-aqg7-3kp1-aaaf
    - VCID-kwjq-nh16-aaac
    - VCID-w2s9-abux-aaae
- purl: pkg:golang/github.com/docker/docker@1.3.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-81mn-mzwm-aaab
    - VCID-mgf4-u476-aaar
- purl: pkg:golang/github.com/docker/docker@1.6.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9ena-9ujd-aaaa
    - VCID-cgzb-3tqk-aaaj
    - VCID-pv9f-a31y-aaac
    - VCID-ymjf-n7j4-aaag
- purl: pkg:golang/github.com/docker/docker@17.6.0-ce
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-x781-mkbk-aaak
- purl: pkg:golang/github.com/docker/docker@18.9.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r9sc-d8bp-aaak
- purl: pkg:golang/github.com/docker/docker@19.3.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9pkn-8q71-aaaa
- purl: pkg:golang/github.com/docker/docker@19.3.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-kb5v-35ak-aaaa
- purl: pkg:golang/github.com/docker/docker@20.10.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-x21b-9yak-aaae
- purl: pkg:golang/github.com/docker/docker@20.10.14
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-dcw7-1988-aaam
- purl: pkg:golang/github.com/docker/docker@20.10.18
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3aaq-ny82-aaag
- purl: pkg:golang/github.com/docker/docker@20.10.20
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-15fa-vy91-aaaa
- purl: pkg:golang/github.com/docker/docker@20.10.24
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-h7tv-gsrm-aaab
    - VCID-jnm2-7vwf-aaaj
    - VCID-vnpd-ha1h-aaab
- purl: pkg:golang/github.com/docker/docker@20.10.27
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-16tu-hyn3-aaaq
- purl: pkg:golang/github.com/docker/docker@20.10.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-98m9-ft46-aaah
    - VCID-qgrb-pu21-aaab
- purl: pkg:golang/github.com/docker/docker@23.0.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6sa-d3zt-aaab
- purl: pkg:golang/github.com/docker/docker@23.0.14
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vr1j-tz9g-aaae
- purl: pkg:golang/github.com/docker/docker@23.0.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vr1j-tz9g-aaae
- purl: pkg:golang/github.com/docker/docker@23.0.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-h7tv-gsrm-aaab
    - VCID-jnm2-7vwf-aaaj
    - VCID-vnpd-ha1h-aaab
- purl: pkg:golang/github.com/docker/docker@23.0.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-16tu-hyn3-aaaq
- purl: pkg:golang/github.com/docker/docker@24.0.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-16tu-hyn3-aaaq
- purl: pkg:golang/github.com/docker/docker@24.0.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-axr6-brgf-aaas
- purl: pkg:golang/github.com/docker/docker@25.0.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-axr6-brgf-aaas
- purl: pkg:golang/github.com/docker/docker@25.0.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6sa-d3zt-aaab
- purl: pkg:golang/github.com/docker/docker@25.0.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vr1j-tz9g-aaae
- purl: pkg:golang/github.com/docker/docker@26.0.0-rc3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6sa-d3zt-aaab
- purl: pkg:golang/github.com/docker/docker@26.0.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-s3pe-n9gh-aaar
- purl: pkg:golang/github.com/docker/docker@26.1.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vr1j-tz9g-aaae
- purl: pkg:golang/github.com/docker/docker@26.1.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vr1j-tz9g-aaae
- purl: pkg:golang/github.com/docker/docker@27.1.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vr1j-tz9g-aaae
- purl: pkg:golang/github.com/docker/docker@27.1.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vr1j-tz9g-aaae
- purl: pkg:golang/github.com/docker/docker@28.0.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-djrp-s85c-wffy
- purl: pkg:golang/github.com/docker/docker@28.3.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vqjj-uy8t-t3bx
