- pkg:alpm/archlinux/grafana@11.6.1-1
- pkg:alpm/archlinux/grafana@5.3.2-1
- pkg:alpm/archlinux/grafana@5.3.4-1
- pkg:alpm/archlinux/grafana@6.3.3-1
- pkg:alpm/archlinux/grafana@6.3.4-1
- pkg:alpm/archlinux/grafana@8.1.5-1
- pkg:alpm/archlinux/grafana@8.1.6-1
- pkg:alpm/archlinux/grafana@8.2.2-1
- pkg:alpm/archlinux/grafana@8.2.3-1
- pkg:alpm/archlinux/grafana@8.2.4-1
- pkg:alpm/archlinux/grafana@8.3.0-1
- pkg:alpm/archlinux/grafana@8.3.1-1
