- purl: pkg:alpm/archlinux/grafana@11.6.1-1
  affected_by_vulnerabilities:
    - VCID-1y2p-hft2-skar
    - VCID-wgcs-d22k-f3ht
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/grafana@5.3.2-1
  affected_by_vulnerabilities:
    - VCID-ejyn-tdpk-aaaj
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/grafana@5.3.4-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ejyn-tdpk-aaaj
- purl: pkg:alpm/archlinux/grafana@6.3.3-1
  affected_by_vulnerabilities:
    - VCID-b6sq-gy55-aaak
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/grafana@6.3.4-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-b6sq-gy55-aaak
- purl: pkg:alpm/archlinux/grafana@8.1.5-1
  affected_by_vulnerabilities:
    - VCID-hwv4-qssy-aaae
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/grafana@8.1.6-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hwv4-qssy-aaae
- purl: pkg:alpm/archlinux/grafana@8.2.2-1
  affected_by_vulnerabilities:
    - VCID-rwx8-y5qh-aaag
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/grafana@8.2.3-1
  affected_by_vulnerabilities:
    - VCID-rj2n-a8bp-aaad
  fixing_vulnerabilities:
    - VCID-rwx8-y5qh-aaag
- purl: pkg:alpm/archlinux/grafana@8.2.4-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rj2n-a8bp-aaad
- purl: pkg:alpm/archlinux/grafana@8.3.0-1
  affected_by_vulnerabilities:
    - VCID-4ba1-gbef-aaaf
    - VCID-bhfv-khhr-aaas
    - VCID-ws8h-wzja-aaan
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/grafana@8.3.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-4ba1-gbef-aaaf
    - VCID-bhfv-khhr-aaas
    - VCID-ws8h-wzja-aaan
