- pkg:golang/github.com/prometheus/prometheus@2.26.1
- pkg:golang/github.com/prometheus/prometheus@2.27.0
- pkg:golang/github.com/prometheus/prometheus@2.27.1
- pkg:golang/github.com/prometheus/prometheus@2.37.4
- pkg:golang/github.com/prometheus/prometheus@2.40.4
- pkg:golang/github.com/prometheus/prometheus@2.7.1
