- purl: pkg:golang/github.com/prometheus/prometheus@2.26.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
- purl: pkg:golang/github.com/prometheus/prometheus@2.27.0
  affected_by_vulnerabilities:
    - VCID-8283-5hs3-aaar
  fixing_vulnerabilities: []
- purl: pkg:golang/github.com/prometheus/prometheus@2.27.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
- purl: pkg:golang/github.com/prometheus/prometheus@2.37.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5rvh-g22e-aaag
- purl: pkg:golang/github.com/prometheus/prometheus@2.40.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5rvh-g22e-aaag
- purl: pkg:golang/github.com/prometheus/prometheus@2.7.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6zg-c9a5-aaah
