- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-14?arch=el8
  affected_by_vulnerabilities:
    - VCID-ew94-7ct2-aaag
    - VCID-fhgh-jkwa-aaah
    - VCID-m1jz-3qsx-aaak
    - VCID-q4bv-fa1u-aaaq
    - VCID-ypnv-um1t-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-16.el8?arch=1
  affected_by_vulnerabilities:
    - VCID-pz2t-umsf-aaan
    - VCID-v537-bky8-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-18.el8?arch=1
  affected_by_vulnerabilities:
    - VCID-86a4-948a-aaaa
    - VCID-wd2x-fkbe-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-20?arch=el8
  affected_by_vulnerabilities:
    - VCID-ad6a-7pdt-aaaf
    - VCID-zxgs-3w22-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-3?arch=el8
  affected_by_vulnerabilities:
    - VCID-gjbz-5q6s-aaad
    - VCID-t2e5-ct53-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.23.0-1?arch=el8
  affected_by_vulnerabilities:
    - VCID-jztw-yc9e-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.23.0-7?arch=el8
  affected_by_vulnerabilities:
    - VCID-ftng-xjpg-aaag
    - VCID-hgur-mt73-aaah
    - VCID-xn43-hdj8-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.23.0-9?arch=el8
  affected_by_vulnerabilities:
    - VCID-6ku7-h49b-aaac
    - VCID-86a4-948a-aaaa
    - VCID-m6nh-ysj9-aaar
    - VCID-uwz1-rspm-aaaj
    - VCID-wd2x-fkbe-aaan
    - VCID-xy23-uwrw-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.7.2-22?arch=el8
  affected_by_vulnerabilities:
    - VCID-t7tm-t2rh-aaah
    - VCID-vkg1-2urs-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.7.2-25?arch=el8
  affected_by_vulnerabilities:
    - VCID-xtcb-c8ut-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.7.2-26?arch=el8
  affected_by_vulnerabilities:
    - VCID-qzf4-cp5y-aaaq
    - VCID-tvy6-7qrk-aaaa
    - VCID-w3w7-upq4-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.7.2-36?arch=el8
  affected_by_vulnerabilities:
    - VCID-xtcb-c8ut-aaag
  fixing_vulnerabilities: []
