- purl: pkg:alpine/cloud-init@21.1-r1?arch=x86&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:alpine/cloud-init@21.1-r1?arch=armhf&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:alpine/cloud-init@21.1-r1?arch=armv7&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:alpine/cloud-init@21.1-r1?arch=s390x&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:alpine/cloud-init@22.2.2-r0?arch=aarch64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:alpine/cloud-init@22.2.2-r0?arch=armhf&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:alpine/cloud-init@22.2.2-r0?arch=armv7&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:alpine/cloud-init@22.2.2-r0?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:alpine/cloud-init@22.2.2-r0?arch=s390x&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:alpine/cloud-init@22.2.2-r0?arch=x86&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:alpine/cloud-init@22.2.2-r0?arch=x86_64&distroversion=edge&reponame=community
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
