- purl: pkg:rpm/redhat/helm@3.13.2-35?arch=el9
  affected_by_vulnerabilities:
    - VCID-6y3x-kyj7-aaaf
    - VCID-te2m-j4fe-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/helm@3.15.4-60?arch=el9
  affected_by_vulnerabilities:
    - VCID-h2kc-9hcv-aaap
    - VCID-qtfg-fbmr-aaaq
    - VCID-qxwq-ayc1-aaak
  fixing_vulnerabilities: []
