- purl: pkg:rpm/redhat/docker@0.11.1-22?arch=el7
  affected_by_vulnerabilities:
    - VCID-2dtu-g7wf-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@1.10.3-57?arch=el7
  affected_by_vulnerabilities:
    - VCID-qu99-ca7p-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@1.3.2-4?arch=el7
  affected_by_vulnerabilities:
    - VCID-aqg7-3kp1-aaaf
    - VCID-w2s9-abux-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@1.4.1-37?arch=el7
  affected_by_vulnerabilities:
    - VCID-81mn-mzwm-aaab
    - VCID-mgf4-u476-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@1.5.0-28?arch=el7
  affected_by_vulnerabilities:
    - VCID-79kw-uyhy-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@1.6.2-14?arch=el7
  affected_by_vulnerabilities:
    - VCID-9ena-9ujd-aaaa
    - VCID-cgzb-3tqk-aaaj
    - VCID-pv9f-a31y-aaac
    - VCID-ymjf-n7j4-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@1.9.1-40?arch=el7
  affected_by_vulnerabilities:
    - VCID-qu99-ca7p-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.12.5-14?arch=el7
  affected_by_vulnerabilities:
    - VCID-funr-5s9t-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.12.6-79.git5680db5?arch=el7
  affected_by_vulnerabilities:
    - VCID-rtmc-4r84-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-102.git7f2769b?arch=el7
  affected_by_vulnerabilities:
    - VCID-1a7v-a4dt-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-104.git4ef4b30?arch=el7
  affected_by_vulnerabilities:
    - VCID-ydxd-x5uj-aaab
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-161.git64e9980?arch=el7_8
  affected_by_vulnerabilities:
    - VCID-e1wn-9ha4-aaah
    - VCID-e3cj-1dr5-aaaj
    - VCID-vvs4-9r5v-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-162.git64e9980?arch=el7_8
  affected_by_vulnerabilities:
    - VCID-7gsk-h9y9-aaar
    - VCID-nbkm-tn5d-aaas
    - VCID-p5st-37fp-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-206.git7d71120?arch=el7_9
  affected_by_vulnerabilities:
    - VCID-6myd-yj9t-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-210.git7d71120?arch=el7_9
  affected_by_vulnerabilities:
    - VCID-h2d7-ph2u-aaah
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-74.git6e3bb8e?arch=el7
  affected_by_vulnerabilities:
    - VCID-njzy-fg53-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-91.git07f3374?arch=el7
  affected_by_vulnerabilities:
    - VCID-rtmc-4r84-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/docker@2:1.13.1-94.gitb2f74b2?arch=el7
  affected_by_vulnerabilities:
    - VCID-q64b-tmvc-aaan
  fixing_vulnerabilities: []
