- purl: pkg:rpm/redhat/prometheus-operator-container@4.10.0-202202160023.p0.g53d6d76.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-66vz-z7v3-aaar
    - VCID-nk3v-tvmw-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.10.0-202207192148.p0.g73ddd44.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-hgur-mt73-aaah
    - VCID-q8fq-1yrc-aaag
    - VCID-uwz1-rspm-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.10.0-202207291908.p0.g73ddd44.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
    - VCID-ftng-xjpg-aaag
    - VCID-xn43-hdj8-aaad
    - VCID-xy23-uwrw-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.10.0-202306170106.p0.ge916c2d.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-cnf3-jr8w-aaag
    - VCID-kye6-bzhe-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.11.0-202208020235.p0.gcb3afa2.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.11.0-202208031306.p0.gcb3afa2.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
    - VCID-m6nh-ysj9-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.11.0-202211072116.p0.gcb3afa2.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-1s79-uech-aaak
    - VCID-24ms-6tr4-aaas
    - VCID-e9sn-uavd-aaah
    - VCID-hhgb-4kt7-aaap
    - VCID-xywa-ra13-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.11.0-202303240327.p0.g5752c42.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-h89x-2eq9-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.11.0-202306270118.p0.g5752c42.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-cnf3-jr8w-aaag
    - VCID-kye6-bzhe-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.12.0-202301042354.p0.g9b41d30.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-1s79-uech-aaak
    - VCID-24ms-6tr4-aaas
    - VCID-5hmn-pv5e-aaad
    - VCID-7jyw-7cbe-aaag
    - VCID-cn47-xzgw-aaas
    - VCID-hhgb-4kt7-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.12.0-202305262042.p0.g57e7c57.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-cnf3-jr8w-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.12.0-202306261055.p0.g57e7c57.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-kye6-bzhe-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.13.0-202304190216.p0.g9cd6788.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-as6k-w71f-aaam
    - VCID-jbdq-mdbt-aaap
    - VCID-qfej-qtan-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.13.0-202307131743.p0.g95a1178.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-s48v-93da-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.13.0-202307242035.p0.g95a1178.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-kye6-bzhe-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.4.0-202101261542?arch=p0
  affected_by_vulnerabilities:
    - VCID-p55m-4uw2-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.5.0-202011132127?arch=p0
  affected_by_vulnerabilities:
    - VCID-ad6a-7pdt-aaaf
    - VCID-zxgs-3w22-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.6.0-202101090040?arch=p0
  affected_by_vulnerabilities:
    - VCID-uwa2-eyvn-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.6.0-202101230113?arch=p0
  affected_by_vulnerabilities:
    - VCID-p55m-4uw2-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.6.0-202208241715.p0.g555d602.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.7.0-202103202139?arch=p0
  affected_by_vulnerabilities:
    - VCID-8dup-t5n7-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.7.0-202108311835.p0.git.1f0fd51.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-hscf-fc4z-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.7.0-202208021424.p0.g1f0fd51.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.8.0-202107291502.p0.git.9d679a1.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-b1t1-32t4-aaaf
    - VCID-gfdc-2q2q-aaak
    - VCID-mtfq-ngz6-aaad
    - VCID-qggy-g6kz-aaaj
    - VCID-tdq5-pwwt-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.8.0-202208241844.p0.g8f4efab.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.9.0-202202120107.p0.g0869335.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-pz2t-umsf-aaan
    - VCID-v537-bky8-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/prometheus-operator-container@4.9.0-202208020055.p0.g170b068.assembly?arch=stream
  affected_by_vulnerabilities:
    - VCID-3jz7-muy2-aaam
  fixing_vulnerabilities: []
