- purl: pkg:npm/%40ag-grid-enterprise/charts@0.0.0
  affected_by_vulnerabilities:
    - VCID-6ux3-96kq-aaak
  fixing_vulnerabilities: []
- purl: pkg:npm/%40ag-grid-enterprise/charts@0.0.1
  affected_by_vulnerabilities:
    - VCID-6ux3-96kq-aaak
  fixing_vulnerabilities: []
- purl: pkg:npm/%40ag-grid-enterprise/charts@0.0.2
  affected_by_vulnerabilities:
    - VCID-6ux3-96kq-aaak
  fixing_vulnerabilities: []
- purl: pkg:npm/%40ag-grid-enterprise/charts@0.0.3
  affected_by_vulnerabilities:
    - VCID-6ux3-96kq-aaak
  fixing_vulnerabilities: []
- purl: pkg:npm/%40ag-grid-enterprise/charts@31.3.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-6ux3-96kq-aaak
- purl: pkg:npm/%40ag-grid-enterprise/charts@32.0.0
  affected_by_vulnerabilities:
    - VCID-6ux3-96kq-aaak
  fixing_vulnerabilities: []
- purl: pkg:npm/%40ag-grid-enterprise/charts@32.0.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-6ux3-96kq-aaak
