- purl: pkg:golang/github.com/grafana/grafana@0.0.0-20240725142242-c326d865c58b
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cw9v-zyy9-53e2
- purl: pkg:golang/github.com/grafana/grafana@0.0.0-20250129224826-70073427041e
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@0.0.0-20250424191517-1f707d16ed5d
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1y2p-hft2-skar
- purl: pkg:golang/github.com/grafana/grafana@0.0.0-20250521183405-c7a690348df7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-854y-ntxd-u7a2
    - VCID-thyy-efdh-4faa
- purl: pkg:golang/github.com/grafana/grafana@0.0.0-20250521211231-e0ba4b480954
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hxkd-w5p1-afam
- purl: pkg:golang/github.com/grafana/grafana@10.0.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ewek-4xjj-aaar
- purl: pkg:golang/github.com/grafana/grafana@10.0.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-grd4-4zeh-aaap
- purl: pkg:golang/github.com/grafana/grafana@10.0.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-s4zu-jbv9-aaaq
    - VCID-w9eb-4e2m-aaam
- purl: pkg:golang/github.com/grafana/grafana@10.1.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ewek-4xjj-aaar
- purl: pkg:golang/github.com/grafana/grafana@10.1.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-grd4-4zeh-aaap
- purl: pkg:golang/github.com/grafana/grafana@10.1.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-s4zu-jbv9-aaaq
    - VCID-w9eb-4e2m-aaam
- purl: pkg:golang/github.com/grafana/grafana@10.2.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ewek-4xjj-aaar
- purl: pkg:golang/github.com/grafana/grafana@10.2.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-grd4-4zeh-aaap
- purl: pkg:golang/github.com/grafana/grafana@10.2.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-s4zu-jbv9-aaaq
    - VCID-w9eb-4e2m-aaam
- purl: pkg:golang/github.com/grafana/grafana@10.3.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ewek-4xjj-aaar
- purl: pkg:golang/github.com/grafana/grafana@10.3.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-grd4-4zeh-aaap
- purl: pkg:golang/github.com/grafana/grafana@10.3.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-s4zu-jbv9-aaaq
    - VCID-w9eb-4e2m-aaam
- purl: pkg:golang/github.com/grafana/grafana@10.4.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@11.0.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@11.0.6%2Bsecurity-01
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bb95-wpjr-gqb7
- purl: pkg:golang/github.com/grafana/grafana@11.1.0
  affected_by_vulnerabilities:
    - VCID-cw9v-zyy9-53e2
  fixing_vulnerabilities: []
- purl: pkg:golang/github.com/grafana/grafana@11.1.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cw9v-zyy9-53e2
- purl: pkg:golang/github.com/grafana/grafana@11.1.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@11.1.2
  affected_by_vulnerabilities:
    - VCID-cw9v-zyy9-53e2
  fixing_vulnerabilities: []
- purl: pkg:golang/github.com/grafana/grafana@11.1.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cw9v-zyy9-53e2
- purl: pkg:golang/github.com/grafana/grafana@11.1.7%2Bsecurity-01
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bb95-wpjr-gqb7
- purl: pkg:golang/github.com/grafana/grafana@11.2.2%2Bsecurity-01
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bb95-wpjr-gqb7
- purl: pkg:golang/github.com/grafana/grafana@11.2.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@11.3.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@11.4.0
  affected_by_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
  fixing_vulnerabilities: []
- purl: pkg:golang/github.com/grafana/grafana@11.4.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@11.6.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hxkd-w5p1-afam
- purl: pkg:golang/github.com/grafana/grafana@12.0.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrr8-9vpb-kufv
- purl: pkg:golang/github.com/grafana/grafana@12.1.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrr8-9vpb-kufv
- purl: pkg:golang/github.com/grafana/grafana@12.2.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrr8-9vpb-kufv
- purl: pkg:golang/github.com/grafana/grafana@1.9.2-0.20240725142242-c326d865c58b
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cw9v-zyy9-53e2
- purl: pkg:golang/github.com/grafana/grafana@1.9.2-0.20250129224826-70073427041e
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hzfu-kwpy-ukeq
- purl: pkg:golang/github.com/grafana/grafana@1.9.2-0.20250514160932-04111e9f2afd
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mrge-m3m1-w3fv
- purl: pkg:golang/github.com/grafana/grafana@1.9.2-0.20250521205822-0ba0b99665a9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cytp-qe58-juc3
- purl: pkg:golang/github.com/grafana/grafana@1.9.2-0.20251106142618-ca5d89812015
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrr8-9vpb-kufv
- purl: pkg:golang/github.com/grafana/grafana@4.6.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-74f2-vsqc-aaaa
- purl: pkg:golang/github.com/grafana/grafana@5.2.0-beta1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tdv4-ytwv-aaac
- purl: pkg:golang/github.com/grafana/grafana@5.2.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-74f2-vsqc-aaaa
- purl: pkg:golang/github.com/grafana/grafana@5.3.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-uz5s-f1cx-aaak
- purl: pkg:golang/github.com/grafana/grafana@6.0.0-beta1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ws3t-kfkn-aaac
    - VCID-xf38-kfaa-aaac
- purl: pkg:golang/github.com/grafana/grafana@6.2.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-k8s3-mmww-aaaa
- purl: pkg:golang/github.com/grafana/grafana@6.4.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-smny-jjyv-aaag
- purl: pkg:golang/github.com/grafana/grafana@6.7.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-g87y-96rb-aaaf
- purl: pkg:golang/github.com/grafana/grafana@6.7.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vn5a-c4pk-aaac
- purl: pkg:golang/github.com/grafana/grafana@6.7.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gbsq-myef-aaaa
- purl: pkg:golang/github.com/grafana/grafana@7.0.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-c6rp-37xf-aaaq
    - VCID-g3cu-aj54-aaar
- purl: pkg:golang/github.com/grafana/grafana@7.0.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gbsq-myef-aaaa
- purl: pkg:golang/github.com/grafana/grafana@7.1.0-beta1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zcrr-8r4t-aaar
- purl: pkg:golang/github.com/grafana/grafana@7.2.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3r9x-k37c-aaaf
    - VCID-4jwf-ed3r-aaas
- purl: pkg:golang/github.com/grafana/grafana@7.4.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-f8jk-rt36-aaaj
- purl: pkg:golang/github.com/grafana/grafana@7.5.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hwv4-qssy-aaae
- purl: pkg:golang/github.com/grafana/grafana@7.5.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-b8kc-15j6-aaan
    - VCID-f5nz-63tm-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.0.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ws8h-wzja-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.1.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-hwv4-qssy-aaae
- purl: pkg:golang/github.com/grafana/grafana@8.1.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ws8h-wzja-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.2.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rj2n-a8bp-aaad
- purl: pkg:golang/github.com/grafana/grafana@8.2.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ws8h-wzja-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.3.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ws8h-wzja-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.3.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9g8p-akhs-aaak
    - VCID-f9d5-f658-aaaf
- purl: pkg:golang/github.com/grafana/grafana@8.3.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-4ba1-gbef-aaaf
- purl: pkg:golang/github.com/grafana/grafana@8.3.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-b8kc-15j6-aaan
    - VCID-f5nz-63tm-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.4.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9g8p-akhs-aaak
    - VCID-f9d5-f658-aaaf
- purl: pkg:golang/github.com/grafana/grafana@8.5.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3axn-amhv-aaaj
    - VCID-u48c-9ys3-aaas
- purl: pkg:golang/github.com/grafana/grafana@8.5.14
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ak74-bz7v-aaab
    - VCID-cqex-t7k3-aaaq
    - VCID-p3gm-x8ng-aaan
    - VCID-yswm-fu1v-aaac
- purl: pkg:golang/github.com/grafana/grafana@8.5.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-heua-x4ft-aaaa
    - VCID-zzee-2a7m-aaaj
- purl: pkg:golang/github.com/grafana/grafana@8.5.16
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bde1-3cj5-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.5.21
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ehtr-y4m2-aaap
    - VCID-wfnz-gcu3-aaam
- purl: pkg:golang/github.com/grafana/grafana@8.5.22
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2aq1-f1ey-aaaf
    - VCID-5ytb-v8a5-aaas
- purl: pkg:golang/github.com/grafana/grafana@8.5.26
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-dzgs-tmuk-aaag
    - VCID-jr7d-baum-aaan
- purl: pkg:golang/github.com/grafana/grafana@8.5.27
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gya3-7evs-aaaq
- purl: pkg:golang/github.com/grafana/grafana@8.5.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9g8p-akhs-aaak
    - VCID-f9d5-f658-aaaf
- purl: pkg:golang/github.com/grafana/grafana@9.0.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9g8p-akhs-aaak
    - VCID-f9d5-f658-aaaf
- purl: pkg:golang/github.com/grafana/grafana@9.0.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3axn-amhv-aaaj
    - VCID-u48c-9ys3-aaas
- purl: pkg:golang/github.com/grafana/grafana@9.1.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3axn-amhv-aaaj
    - VCID-u48c-9ys3-aaas
- purl: pkg:golang/github.com/grafana/grafana@9.1.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ak74-bz7v-aaab
    - VCID-cqex-t7k3-aaaq
    - VCID-p3gm-x8ng-aaan
    - VCID-yswm-fu1v-aaac
- purl: pkg:golang/github.com/grafana/grafana@9.2.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vu7m-19m3-aaap
- purl: pkg:golang/github.com/grafana/grafana@9.2.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ehtr-y4m2-aaap
    - VCID-wfnz-gcu3-aaam
- purl: pkg:golang/github.com/grafana/grafana@9.2.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2aq1-f1ey-aaaf
    - VCID-5ytb-v8a5-aaas
- purl: pkg:golang/github.com/grafana/grafana@9.2.19
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-dzgs-tmuk-aaag
    - VCID-jr7d-baum-aaan
- purl: pkg:golang/github.com/grafana/grafana@9.2.20
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gya3-7evs-aaaq
- purl: pkg:golang/github.com/grafana/grafana@9.2.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bhhu-gbkt-aaad
    - VCID-heua-x4ft-aaaa
    - VCID-zzee-2a7m-aaaj
- purl: pkg:golang/github.com/grafana/grafana@9.2.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bde1-3cj5-aaan
- purl: pkg:golang/github.com/grafana/grafana@9.3.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2aq1-f1ey-aaaf
    - VCID-5ytb-v8a5-aaas
- purl: pkg:golang/github.com/grafana/grafana@9.3.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-dzgs-tmuk-aaag
    - VCID-jr7d-baum-aaan
- purl: pkg:golang/github.com/grafana/grafana@9.3.16
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gya3-7evs-aaaq
- purl: pkg:golang/github.com/grafana/grafana@9.3.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vu7m-19m3-aaap
- purl: pkg:golang/github.com/grafana/grafana@9.3.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ehtr-y4m2-aaap
    - VCID-wfnz-gcu3-aaam
- purl: pkg:golang/github.com/grafana/grafana@9.4.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-dzgs-tmuk-aaag
    - VCID-jr7d-baum-aaan
    - VCID-q6c9-cvs6-aaaj
- purl: pkg:golang/github.com/grafana/grafana@9.4.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gya3-7evs-aaaq
- purl: pkg:golang/github.com/grafana/grafana@9.4.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2aq1-f1ey-aaaf
- purl: pkg:golang/github.com/grafana/grafana@9.5.16
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ewek-4xjj-aaar
- purl: pkg:golang/github.com/grafana/grafana@9.5.18
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-s4zu-jbv9-aaaq
    - VCID-w9eb-4e2m-aaam
- purl: pkg:golang/github.com/grafana/grafana@9.5.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-dzgs-tmuk-aaag
    - VCID-jr7d-baum-aaan
    - VCID-q6c9-cvs6-aaaj
- purl: pkg:golang/github.com/grafana/grafana@9.5.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-grd4-4zeh-aaap
