- pkg:deb/debian/docker-compose@0?distro=trixie
- pkg:deb/debian/docker-compose@1.25.0-1?distro=trixie
- pkg:deb/debian/docker-compose@1.29.2-3?distro=trixie
- pkg:deb/debian/docker-compose@2.26.1-4?distro=trixie
- pkg:deb/debian/docker-compose@2.32.4-3?distro=trixie
