- purl: pkg:golang/github.com/mattermost/mattermost-plugin-playbooks@1.41.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-frz4-m3qv-m7ec
    - VCID-p7e9-qwvf-sbat
    - VCID-x34t-pm7v-7fg6
