- pkg:rpm/redhat/prometheus@container-v2.12?arch=1-2
- pkg:rpm/redhat/prometheus@container-v2.12?arch=3-6
- pkg:rpm/redhat/prometheus@container-v2.12?arch=5-4
- pkg:rpm/redhat/prometheus@container-v2.13?arch=4-9
- pkg:rpm/redhat/prometheus@container-v2.5?arch=8-4
- pkg:rpm/redhat/prometheus@container-v2.5?arch=0-14
- pkg:rpm/redhat/prometheus@container-v2.6?arch=7-6
- pkg:rpm/redhat/prometheus@container-v2.6?arch=5-5
- pkg:rpm/redhat/prometheus@container-v2.6?arch=0-8
- pkg:rpm/redhat/prometheus@container-v2.7?arch=7-5
- pkg:rpm/redhat/prometheus@container-v2.8?arch=2-2
