- purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.8.0-1?distro=stretch
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.8.0-1
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1?distro=sid
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1?distro=stretch
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.0-3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.1-1?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.1-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.12.2-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.12.2-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.12.2-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.12.2-4?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.13.0-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.13.1-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.14.0-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.14.0-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.14.0-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.14.0-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.15.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.15.1-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.16.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.16.0-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.16.0-4?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.17.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.17.0-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.18.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.19.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.19.0-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.19.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.19.1-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.20.3-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.20.4-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.20.5-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.21.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.2.1-3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=stretch
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=sid
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=trixie
  affected_by_vulnerabilities:
    - VCID-tzxf-ndv1-aaan
  fixing_vulnerabilities: []
