- pkg:alpm/archlinux/ansible@2.10.5-1
- pkg:alpm/archlinux/ansible@2.10.7-1
- pkg:alpm/archlinux/ansible@2.2.0.0-1
- pkg:alpm/archlinux/ansible@2.2.1.0rc5-3
- pkg:alpm/archlinux/ansible@3.1.0-1
- pkg:alpm/archlinux/ansible@4.0.0-1
