- purl: pkg:alpm/archlinux/ansible@2.10.5-1
  affected_by_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
    - VCID-hx4y-7eby-aaad
    - VCID-qzhf-2cvf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/ansible@2.10.7-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-a6gj-c3pa-aaad
    - VCID-hx4y-7eby-aaad
    - VCID-qzhf-2cvf-aaaf
- purl: pkg:alpm/archlinux/ansible@2.2.0.0-1
  affected_by_vulnerabilities:
    - VCID-scu2-mz1c-aaan
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/ansible@2.2.1.0rc5-3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-scu2-mz1c-aaan
- purl: pkg:alpm/archlinux/ansible@3.1.0-1
  affected_by_vulnerabilities:
    - VCID-ugk3-fc38-aaak
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/ansible@4.0.0-1
  affected_by_vulnerabilities:
    - VCID-wvuy-s63y-aaan
    - VCID-yuxd-4zd7-aaab
  fixing_vulnerabilities: []
