- pkg:rpm/redhat/openshift-istio-prometheus-rhel8@container-2.2?arch=8-4
- pkg:rpm/redhat/openshift-istio-prometheus-rhel8@container-2.2?arch=7-7
- pkg:rpm/redhat/openshift-istio-prometheus-rhel8@container-2.2?arch=2-4
- pkg:rpm/redhat/openshift-istio-prometheus-rhel8@container-2.3?arch=5-4
- pkg:rpm/redhat/openshift-istio-prometheus-rhel8@container-2.3?arch=1-6
