- purl: pkg:deb/debian/cloud-init@0?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@0?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@0.7.1-1?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
- purl: pkg:deb/debian/cloud-init@0.7.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
- purl: pkg:deb/debian/cloud-init@0.7.1-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
- purl: pkg:deb/debian/cloud-init@0.7.2-3~bpo70%2B1
  affected_by_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/cloud-init@0.7.6~bzr976-2
  affected_by_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/cloud-init@0.7.7~bzr1156-1~bpo8%2B1
  affected_by_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/cloud-init@0.7.9-2
  affected_by_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/cloud-init@0.7.9-2?distro=stretch
  affected_by_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-rgk6-gc76-aaar
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-nphr-p5x9-aaaj
- purl: pkg:deb/debian/cloud-init@0.7.9-2%2Bdeb9u1?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:deb/debian/cloud-init@18.3-6?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@18.3-6?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@18.3-6?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@19.4-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
- purl: pkg:deb/debian/cloud-init@19.4-2?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
- purl: pkg:deb/debian/cloud-init@19.4-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
- purl: pkg:deb/debian/cloud-init@20.2-2~bpo10%2B1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=trixie
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
  fixing_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@20.4.1-2?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:deb/debian/cloud-init@20.4.1-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:deb/debian/cloud-init@20.4.1-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1
  affected_by_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
- purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-b9jd-wm14-kkb5
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.2-1?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
- purl: pkg:deb/debian/cloud-init@22.2-1~bpo11%2B1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@22.2-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.2-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.2-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.2-3.1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.4.2-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.4.2-1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.4.2-1
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/cloud-init@22.4.2-1%2Bdeb12u1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.4.2-1%2Bdeb12u1
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/cloud-init@22.4.2-1%2Bdeb12u2?distro=trixie
  affected_by_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-b9jd-wm14-kkb5
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.4.2-1%2Bdeb12u2
  affected_by_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@22.4.2-1%2Bdeb12u3?distro=trixie
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-b9jd-wm14-kkb5
    - VCID-bjwp-wq7y-aaad
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@22.4.2-1%2Bdeb12u3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@23.2-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@23.2.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@23.3.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@23.3.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@24.1.3-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.4-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.4-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.4-2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@24.1.6-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.7-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.7-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.1.7-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.2-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@24.2-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.3.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@24.3.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.3.1-2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@24.3.1-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.4-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@24.4-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@24.4.1-2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@25.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@25.1.1-1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities:
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@25.1.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
- purl: pkg:deb/debian/cloud-init@25.1.4-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-b9jd-wm14-kkb5
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@25.1.4-1%2Bdeb13u1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-b9jd-wm14-kkb5
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@25.2-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-b9jd-wm14-kkb5
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@25.3-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-b9jd-wm14-kkb5
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
- purl: pkg:deb/debian/cloud-init@25.3-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2z9c-n911-w3ee
    - VCID-5n5e-af5d-aaae
    - VCID-5sez-wgc8-aaaq
    - VCID-b9jd-wm14-kkb5
    - VCID-bjwp-wq7y-aaad
    - VCID-mkrm-q7yw-aaaq
    - VCID-nphr-p5x9-aaaj
    - VCID-rgk6-gc76-aaar
    - VCID-zbat-x8sj-aaae
