- purl: pkg:gem/dependabot-core@0.119.0
  affected_by_vulnerabilities:
    - VCID-u431-gn6w-aaag
  fixing_vulnerabilities: []
- purl: pkg:gem/dependabot-core@0.125.1
  affected_by_vulnerabilities:
    - VCID-u431-gn6w-aaag
  fixing_vulnerabilities: []
