- purl: pkg:golang/k8s.io/kubernetes@0.16.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zgmm-v18j-aaaq
- purl: pkg:golang/k8s.io/kubernetes@0.17.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zgmm-v18j-aaaq
- purl: pkg:golang/k8s.io/kubernetes@0.18.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zgmm-v18j-aaaq
- purl: pkg:golang/k8s.io/kubernetes@1.10.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mq5e-g8uf-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.1.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3guf-r76t-aaar
- purl: pkg:golang/k8s.io/kubernetes@1.11.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mq5e-g8uf-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.11.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-57ut-z218-aaab
- purl: pkg:golang/k8s.io/kubernetes@1.11.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3nc4-y8bt-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.12.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-h94n-73z9-aaak
- purl: pkg:golang/k8s.io/kubernetes@1.12.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-57ut-z218-aaab
- purl: pkg:golang/k8s.io/kubernetes@1.12.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3nc4-y8bt-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.13.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-h94n-73z9-aaak
- purl: pkg:golang/k8s.io/kubernetes@1.13.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5s9t-5zss-aaab
- purl: pkg:golang/k8s.io/kubernetes@1.13.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xtcb-c8ut-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.13.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-57ut-z218-aaab
- purl: pkg:golang/k8s.io/kubernetes@1.13.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3nc4-y8bt-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.14.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5s9t-5zss-aaab
- purl: pkg:golang/k8s.io/kubernetes@1.14.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xtcb-c8ut-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.15.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1ub7-xfyy-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.15.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fc1k-7qvj-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.15.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xtcb-c8ut-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.16.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5s9t-5zss-aaab
- purl: pkg:golang/k8s.io/kubernetes@1.16.0-beta.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-59mj-gxpv-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.16.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xt74-eht1-aaac
- purl: pkg:golang/k8s.io/kubernetes@1.16.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zgmm-v18j-aaaq
- purl: pkg:golang/k8s.io/kubernetes@1.16.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xtcb-c8ut-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.16.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1ub7-xfyy-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.16.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fc1k-7qvj-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.17.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1ub7-xfyy-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.17.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fc1k-7qvj-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.17.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xt74-eht1-aaac
- purl: pkg:golang/k8s.io/kubernetes@1.17.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zgmm-v18j-aaaq
- purl: pkg:golang/k8s.io/kubernetes@1.18.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fc1k-7qvj-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.18.18
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vh2m-gm2t-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.18.19
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7s41-h8fk-aaap
    - VCID-a2cq-h1yy-aaak
- purl: pkg:golang/k8s.io/kubernetes@1.18.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xt74-eht1-aaac
- purl: pkg:golang/k8s.io/kubernetes@1.18.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zgmm-v18j-aaaq
- purl: pkg:golang/k8s.io/kubernetes@1.19.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vh2m-gm2t-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.19.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7s41-h8fk-aaap
    - VCID-a2cq-h1yy-aaak
- purl: pkg:golang/k8s.io/kubernetes@1.19.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5qv3-y4v1-aaaf
- purl: pkg:golang/k8s.io/kubernetes@1.20.0-alpha.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1y4g-d4ck-aaaq
- purl: pkg:golang/k8s.io/kubernetes@1.20.0-alpha.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2qwr-a8ug-aaar
- purl: pkg:golang/k8s.io/kubernetes@1.20.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5qv3-y4v1-aaaf
- purl: pkg:golang/k8s.io/kubernetes@1.20.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vh2m-gm2t-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.20.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7s41-h8fk-aaap
    - VCID-a2cq-h1yy-aaak
- purl: pkg:golang/k8s.io/kubernetes@1.2.0-alpha.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fu1b-qhxq-aaad
- purl: pkg:golang/k8s.io/kubernetes@1.21.0
  affected_by_vulnerabilities:
    - VCID-a2cq-h1yy-aaak
  fixing_vulnerabilities:
    - VCID-tdyk-k3xg-aaac
- purl: pkg:golang/k8s.io/kubernetes@1.21.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7s41-h8fk-aaap
    - VCID-a2cq-h1yy-aaak
- purl: pkg:golang/k8s.io/kubernetes@1.21.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5qv3-y4v1-aaaf
- purl: pkg:golang/k8s.io/kubernetes@1.22.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5qv3-y4v1-aaaf
- purl: pkg:golang/k8s.io/kubernetes@1.24.14
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gjea-gk4t-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.24.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-aafc-9fsp-aaam
    - VCID-q2tw-bu8w-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.24.17
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gd4c-1bgt-aaap
    - VCID-sxqk-vgbd-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.25.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gjea-gk4t-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.25.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-aafc-9fsp-aaam
    - VCID-q2tw-bu8w-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.25.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gd4c-1bgt-aaap
    - VCID-sxqk-vgbd-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.25.16
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-yvgr-mtfs-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.26.0-alpha.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fjyn-e4r9-aaaq
- purl: pkg:golang/k8s.io/kubernetes@1.26.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-yvgr-mtfs-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.26.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gjea-gk4t-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.26.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-aafc-9fsp-aaam
    - VCID-q2tw-bu8w-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.26.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gd4c-1bgt-aaap
    - VCID-sxqk-vgbd-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.27.0-alpha.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bwwf-kdbu-aaad
- purl: pkg:golang/k8s.io/kubernetes@1.27.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-brrq-5mfd-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.27.16
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fj1f-ynah-aaam
- purl: pkg:golang/k8s.io/kubernetes@1.27.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gjea-gk4t-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.27.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-aafc-9fsp-aaam
    - VCID-q2tw-bu8w-aaah
- purl: pkg:golang/k8s.io/kubernetes@1.27.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gd4c-1bgt-aaap
    - VCID-sxqk-vgbd-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.27.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-yvgr-mtfs-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.28.0
  affected_by_vulnerabilities:
    - VCID-gd4c-1bgt-aaap
    - VCID-sxqk-vgbd-aaaj
  fixing_vulnerabilities: []
- purl: pkg:golang/k8s.io/kubernetes@1.28.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-gd4c-1bgt-aaap
    - VCID-sxqk-vgbd-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.28.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-89k2-3ctq-byfj
    - VCID-fj1f-ynah-aaam
- purl: pkg:golang/k8s.io/kubernetes@1.28.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-yvgr-mtfs-aaag
- purl: pkg:golang/k8s.io/kubernetes@1.28.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-brrq-5mfd-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.29.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9q8a-z2v1-4kar
- purl: pkg:golang/k8s.io/kubernetes@1.29.14
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xakj-dx9e-sbdz
- purl: pkg:golang/k8s.io/kubernetes@1.29.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-brrq-5mfd-aaas
- purl: pkg:golang/k8s.io/kubernetes@1.29.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-89k2-3ctq-byfj
    - VCID-fj1f-ynah-aaam
- purl: pkg:golang/k8s.io/kubernetes@1.30.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xakj-dx9e-sbdz
- purl: pkg:golang/k8s.io/kubernetes@1.30.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-89k2-3ctq-byfj
    - VCID-fj1f-ynah-aaam
- purl: pkg:golang/k8s.io/kubernetes@1.30.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9q8a-z2v1-4kar
- purl: pkg:golang/k8s.io/kubernetes@1.31.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jbwv-u9nt-5yc9
- purl: pkg:golang/k8s.io/kubernetes@1.31.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9q8a-z2v1-4kar
- purl: pkg:golang/k8s.io/kubernetes@1.31.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xakj-dx9e-sbdz
- purl: pkg:golang/k8s.io/kubernetes@1.32.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9q8a-z2v1-4kar
- purl: pkg:golang/k8s.io/kubernetes@1.32.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rr9h-863j-nuah
- purl: pkg:golang/k8s.io/kubernetes@1.32.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-xakj-dx9e-sbdz
- purl: pkg:golang/k8s.io/kubernetes@1.32.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-byan-qnwc-3ub4
- purl: pkg:golang/k8s.io/kubernetes@1.32.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jbwv-u9nt-5yc9
- purl: pkg:golang/k8s.io/kubernetes@1.33.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-byan-qnwc-3ub4
- purl: pkg:golang/k8s.io/kubernetes@1.33.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jbwv-u9nt-5yc9
- purl: pkg:golang/k8s.io/kubernetes@1.33.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rr9h-863j-nuah
- purl: pkg:golang/k8s.io/kubernetes@1.34.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rr9h-863j-nuah
- purl: pkg:golang/k8s.io/kubernetes@1.5.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-d4bu-e64f-aaak
- purl: pkg:golang/k8s.io/kubernetes@1.7.14
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-j9nb-qsnr-aaad
- purl: pkg:golang/k8s.io/kubernetes@1.8.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-j9nb-qsnr-aaad
- purl: pkg:golang/k8s.io/kubernetes@1.9.10
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-mq5e-g8uf-aaaj
- purl: pkg:golang/k8s.io/kubernetes@1.9.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-j9nb-qsnr-aaad
- purl: pkg:golang/k8s.io/kubernetes@1.9.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-v7bw-nwrc-aaan
