- pkg:golang/github.com/traefik/traefik@1.6.6
- pkg:golang/github.com/traefik/traefik@1.7.12
- pkg:golang/github.com/traefik/traefik@1.7.26
- pkg:golang/github.com/traefik/traefik@2.10.5
- pkg:golang/github.com/traefik/traefik@2.11.2
- pkg:golang/github.com/traefik/traefik@2.11.4
- pkg:golang/github.com/traefik/traefik@2.11.6
- pkg:golang/github.com/traefik/traefik@2.11.9
- pkg:golang/github.com/traefik/traefik@2.1.4
- pkg:golang/github.com/traefik/traefik@3.0.0-beta4
- pkg:golang/github.com/traefik/traefik@3.0.4
- pkg:golang/github.com/traefik/traefik@3.1.0-rc3
