- purl: pkg:golang/github.com/traefik/traefik@1.6.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vpfd-rq1j-aaaq
- purl: pkg:golang/github.com/traefik/traefik@1.7.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rbtx-b52f-aaan
- purl: pkg:golang/github.com/traefik/traefik@1.7.26
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zyqr-cfmr-aaaa
- purl: pkg:golang/github.com/traefik/traefik@2.10.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-4429-ymqx-aaae
- purl: pkg:golang/github.com/traefik/traefik@2.11.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vqv3-5g7z-aaaj
- purl: pkg:golang/github.com/traefik/traefik@2.11.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jz9b-xau1-aaak
- purl: pkg:golang/github.com/traefik/traefik@2.11.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrdg-musw-aaad
- purl: pkg:golang/github.com/traefik/traefik@2.11.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-g4ue-jpuh-efcu
- purl: pkg:golang/github.com/traefik/traefik@2.1.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-qqdm-qe6u-aaab
- purl: pkg:golang/github.com/traefik/traefik@3.0.0-beta4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-4429-ymqx-aaae
- purl: pkg:golang/github.com/traefik/traefik@3.0.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrdg-musw-aaad
- purl: pkg:golang/github.com/traefik/traefik@3.1.0-rc3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zrdg-musw-aaad
