- purl: pkg:golang/k8s.io/kubernetes/pkg/kubelet@1.16.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2xe9-pbxb-aaap
- purl: pkg:golang/k8s.io/kubernetes/pkg/kubelet@1.17.9
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2xe9-pbxb-aaap
- purl: pkg:golang/k8s.io/kubernetes/pkg/kubelet@1.18.6
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2xe9-pbxb-aaap
