- pkg:rpm/redhat/prometheus-operator@container-v3.11?arch=141-2
- pkg:rpm/redhat/prometheus-operator@container-v3.11?arch=146-2
- pkg:rpm/redhat/prometheus-operator@container-v3.11?arch=82-3
- pkg:rpm/redhat/prometheus-operator@container-v3.11?arch=98-7
- pkg:rpm/redhat/prometheus-operator@container-v4.1?arch=14-201908291507
- pkg:rpm/redhat/prometheus-operator@container-v4.2?arch=4-201911050122
- pkg:rpm/redhat/prometheus-operator@container-v4.3?arch=2-202002112006
