- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.17.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.17.1
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.17.2
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.18.0
