- purl: pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.17.0
  affected_by_vulnerabilities:
    - VCID-48mb-hd2h-aaae
  fixing_vulnerabilities: []
- purl: pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.17.1
  affected_by_vulnerabilities:
    - VCID-48mb-hd2h-aaae
  fixing_vulnerabilities: []
- purl: pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.17.2
  affected_by_vulnerabilities:
    - VCID-48mb-hd2h-aaae
  fixing_vulnerabilities: []
- purl: pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.18.0
  affected_by_vulnerabilities:
    - VCID-48mb-hd2h-aaae
  fixing_vulnerabilities: []
