- purl: pkg:golang/helm.sh/helm/v3@3.1.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-chcx-jfyc-aaaf
- purl: pkg:golang/helm.sh/helm/v3@3.10.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bx41-huqn-aaaq
    - VCID-cf42-nk8j-aaad
    - VCID-ybss-r2p5-aaaa
- purl: pkg:golang/helm.sh/helm/v3@3.11.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9qu2-n6vn-aaar
- purl: pkg:golang/helm.sh/helm/v3@3.1.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1t5k-9q59-aaaj
- purl: pkg:golang/helm.sh/helm/v3@3.14.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-fhrk-bupu-aaap
- purl: pkg:golang/helm.sh/helm/v3@3.14.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-f5y6-ydz9-aaah
- purl: pkg:golang/helm.sh/helm/v3@3.17.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9t86-4kjg-8fe7
    - VCID-f7vm-4n7d-ekaq
- purl: pkg:golang/helm.sh/helm/v3@3.17.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-x3fm-nj4g-xufr
- purl: pkg:golang/helm.sh/helm/v3@3.18.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-x3fm-nj4g-xufr
- purl: pkg:golang/helm.sh/helm/v3@3.18.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-dkxv-6q2t-9qcc
    - VCID-qjb2-1pu5-zub8
- purl: pkg:golang/helm.sh/helm/v3@3.2.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7nyg-2t2y-aaad
- purl: pkg:golang/helm.sh/helm/v3@3.3.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bgmq-vjap-aaaj
    - VCID-ctxh-2dy7-aaaa
    - VCID-dvn7-nnqz-aaak
    - VCID-hcs8-kr96-aaap
- purl: pkg:golang/helm.sh/helm/v3@3.5.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zv63-hf87-aaam
- purl: pkg:golang/helm.sh/helm/v3@3.6.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bhjy-uks6-aaaa
    - VCID-qve5-4atd-aaac
- purl: pkg:golang/helm.sh/helm/v3@3.9.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-66z1-61r5-aaap
