- purl: pkg:rpm/redhat/python-prometheus_client@0.6.0-1?arch=el8ost
  affected_by_vulnerabilities:
    - VCID-2cqt-v8wb-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/python-prometheus_client@0.7.1-3?arch=el8
  affected_by_vulnerabilities:
    - VCID-7jyw-7cbe-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/python-prometheus_client@0.7.1-3?arch=el9
  affected_by_vulnerabilities:
    - VCID-pn75-hsb4-aaac
  fixing_vulnerabilities: []
