- purl: pkg:golang/github.com/containous/traefik/v2/pkg/api@2.2.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zyqr-cfmr-aaaa
- purl: pkg:golang/github.com/containous/traefik/v2/pkg/api@2.3.0-rc3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zyqr-cfmr-aaaa
