- pkg:deb/debian/ansible@0?distro=stretch
- pkg:deb/debian/ansible@0?distro=sid
- pkg:deb/debian/ansible@0?distro=trixie
- pkg:deb/debian/ansible@10.0.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@10.0.1%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@10.1.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@10.1.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@10.5.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@10.5.0%2Bdfsg-2?distro=sid
- pkg:deb/debian/ansible@10.6.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@11.1.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@11.2.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@12.0.0~a1%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@1.3.4%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@1.3.4%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@1.3.4%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@1.5.4%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@1.5.4%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@1.5.4%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@1.5.5%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@1.5.5%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@1.5.5%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@1.6.6%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@1.6.6%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@1.6.6%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@1.6.8%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@1.6.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@1.6.8%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@1.7.0%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@1.7.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@1.7.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@1.7.2%2Bdfsg-2
- pkg:deb/debian/ansible@1.7.2%2Bdfsg-2~bpo70%2B1
- pkg:deb/debian/ansible@1.9.2%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@1.9.2%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@1.9.2%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.0.1.0-2?distro=stretch
- pkg:deb/debian/ansible@2.0.1.0-2?distro=sid
- pkg:deb/debian/ansible@2.0.1.0-2?distro=trixie
- pkg:deb/debian/ansible@2.10.7-1?distro=trixie
- pkg:deb/debian/ansible@2.10.7-1?distro=sid
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.17%2Bdfsg-0%2Bdeb11u1
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.17%2Bdfsg-0%2Bdeb11u1?distro=trixie
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.17%2Bdfsg-0%2Bdeb11u1?distro=sid
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.17%2Bdfsg-0%2Bdeb11u2?distro=trixie
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.2.0.0-1?distro=stretch
- pkg:deb/debian/ansible@2.2.0.0-1?distro=sid
- pkg:deb/debian/ansible@2.2.0.0-1?distro=trixie
- pkg:deb/debian/ansible@2.2.0.0-3?distro=stretch
- pkg:deb/debian/ansible@2.2.0.0-3?distro=sid
- pkg:deb/debian/ansible@2.2.0.0-3?distro=trixie
- pkg:deb/debian/ansible@2.2.0.0-4?distro=stretch
- pkg:deb/debian/ansible@2.2.0.0-4?distro=sid
- pkg:deb/debian/ansible@2.2.0.0-4?distro=trixie
- pkg:deb/debian/ansible@2.2.1.0-2?distro=stretch
- pkg:deb/debian/ansible@2.2.1.0-2?distro=sid
- pkg:deb/debian/ansible@2.2.1.0-2?distro=trixie
- pkg:deb/debian/ansible@2.2.1.0-2~bpo8%2B1
- pkg:deb/debian/ansible@2.2.1.0-2%2Bdeb9u1
- pkg:deb/debian/ansible@2.2.1.0-2%2Bdeb9u1?distro=stretch
- pkg:deb/debian/ansible@2.2.1.0-2%2Bdeb9u2?distro=stretch
- pkg:deb/debian/ansible@2.3.1.0%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.3.1.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.3.1.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.4.2.0%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.4.2.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.4.2.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.5.5%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.5.5%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.5.5%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.6.1%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.6.1%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.6.1%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.7.1%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.7.1%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.1%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.7.5%2Bdfsg-1~bpo9%2B1
- pkg:deb/debian/ansible@2.7.6%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.7.6%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.6%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=stretch
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=trixie
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u2?distro=trixie
- pkg:deb/debian/ansible@2.8.3%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.8.3%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.8.3%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.8.6%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.8.6%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.8.6%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.9.13%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.9.13%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.9.13%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.9.16%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.9.16%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.9.16%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.9.16%2Bdfsg-1~bpo10%2B2
- pkg:deb/debian/ansible@2.9.2%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.9.2%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.9.2%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.9.4%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.9.4%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.9.4%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.9.6%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.9.6%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.9.6%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@2.9.7%2Bdfsg-1?distro=stretch
- pkg:deb/debian/ansible@2.9.7%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.9.7%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@5.4.0-1?distro=sid
- pkg:deb/debian/ansible@5.4.0-1?distro=trixie
- pkg:deb/debian/ansible@5.5.0-1?distro=sid
- pkg:deb/debian/ansible@5.5.0-1?distro=stretch
- pkg:deb/debian/ansible@6.3.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@6.4.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@7.0.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@7.0.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@7.0.0%2Bdfsg-2?distro=sid
- pkg:deb/debian/ansible@7.1.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@7.2.0%2Bdfsg-2?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@7.7.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@7.7.0%2Bdfsg-2?distro=trixie
- pkg:deb/debian/ansible@7.7.0%2Bdfsg-3?distro=trixie
- pkg:deb/debian/ansible@7.7.0%2Bdfsg-3
- pkg:deb/debian/ansible@7.7.0%2Bdfsg-3%2Bdeb12u1?distro=trixie
- pkg:deb/debian/ansible@7.7.0%2Bdfsg-3%2Bdeb12u1?distro=sid
- pkg:deb/debian/ansible@7.7.0%2Bdfsg-3%2Bdeb12u1
- pkg:deb/debian/ansible@9.4.0%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@9.4.0%2Bdfsg-1
- pkg:deb/debian/ansible@9.4.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@9.5.1%2Bdfsg-1?distro=trixie
- pkg:deb/debian/ansible@9.5.1%2Bdfsg-1
