- purl: pkg:golang/helm.sh/helm@2.12.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-341w-tmkf-aaaj
- purl: pkg:golang/helm.sh/helm@2.15.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-e366-qck7-aaak
- purl: pkg:golang/helm.sh/helm@2.16.11
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bgmq-vjap-aaaj
    - VCID-ctxh-2dy7-aaaa
    - VCID-dvn7-nnqz-aaak
    - VCID-hcs8-kr96-aaap
- purl: pkg:golang/helm.sh/helm@2.7.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-7kkf-ahke-aaaq
