- purl: pkg:golang/github.com/netlify/gotrue@1.0.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-z7pe-479f-aaaj
- purl: pkg:golang/github.com/netlify/gotrue@1.0.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5qt8-mga4-aaap
