- pkg:deb/ubuntu/prometheus@0.14.0%2Bds-1
- pkg:deb/ubuntu/prometheus@0.15.1%2Bds-2
- pkg:deb/ubuntu/prometheus@0.16.2%2Bds-1
- pkg:deb/ubuntu/prometheus@0.16.2%2Bds-1ubuntu1
- pkg:deb/ubuntu/prometheus@0.18.0%2Bds-1
- pkg:deb/ubuntu/prometheus@0.18.0%2Bds-2
- pkg:deb/ubuntu/prometheus@0.19.2%2Bds-1
- pkg:deb/ubuntu/prometheus@0.19.2%2Bds-2
- pkg:deb/ubuntu/prometheus@0.19.3%2Bds-1
- pkg:deb/ubuntu/prometheus@0.20.0%2Bds-1
- pkg:deb/ubuntu/prometheus@1.0.0%2Bds-1
- pkg:deb/ubuntu/prometheus@1.0.1%2Bds-1
- pkg:deb/ubuntu/prometheus@1.2.2%2Bds-1
- pkg:deb/ubuntu/prometheus@1.2.3%2Bds-2
- pkg:deb/ubuntu/prometheus@1.2.3%2Bds2-1
- pkg:deb/ubuntu/prometheus@1.2.3%2Bds2-2
- pkg:deb/ubuntu/prometheus@1.2.3%2Bds2-3
- pkg:deb/ubuntu/prometheus@1.2.3%2Bds2-4
- pkg:deb/ubuntu/prometheus@1.2.3%2Bds2-5
- pkg:deb/ubuntu/prometheus@1.5.0%2Bds-1
- pkg:deb/ubuntu/prometheus@1.5.2%2Bds-1
- pkg:deb/ubuntu/prometheus@1.5.2%2Bds-2
- pkg:deb/ubuntu/prometheus@1.6.2%2Bds-2
- pkg:deb/ubuntu/prometheus@1.6.3%2Bds-1
- pkg:deb/ubuntu/prometheus@1.6.3%2Bds2-1
- pkg:deb/ubuntu/prometheus@1.7.1%2Bds-1
- pkg:deb/ubuntu/prometheus@1.8.1%2Bds-2
- pkg:deb/ubuntu/prometheus@2.0.0%2Bds3-1
- pkg:deb/ubuntu/prometheus@2.1.0%2Bds-1
- pkg:deb/ubuntu/prometheus@2.2.1%2Bds-2
- pkg:deb/ubuntu/prometheus@2.3.0%2Bds-1
- pkg:deb/ubuntu/prometheus@2.3.1%2Bds-1
- pkg:deb/ubuntu/prometheus@2.3.2%2Bds-1
- pkg:deb/ubuntu/prometheus@2.4.3%2Bds-2
- pkg:deb/ubuntu/prometheus@2.5.0%2Bds-1
- pkg:deb/ubuntu/prometheus@2.5.0%2Bds-2
- pkg:deb/ubuntu/prometheus@2.6.0%2Bds-1
- pkg:deb/ubuntu/prometheus@2.7.1%2Bds-1
- pkg:deb/ubuntu/prometheus@2.7.1%2Bds-3
