- purl: pkg:rpm/redhat/rubygem-prometheus-client@0.8.0-1?arch=el7
  affected_by_vulnerabilities:
    - VCID-kac9-8rqu-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/rubygem-prometheus-client@1.0.0-3?arch=el8sat
  affected_by_vulnerabilities:
    - VCID-ftmk-wbwx-aaar
    - VCID-rsxn-xh5p-rqgj
  fixing_vulnerabilities: []
