- purl: pkg:golang/github.com/prometheus/prometheus/v2@2.37.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5rvh-g22e-aaag
- purl: pkg:golang/github.com/prometheus/prometheus/v2@2.40.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-5rvh-g22e-aaag
