- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.10.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.10.0-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.11.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.11.0-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.12.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.13.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.13.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.14.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.14.0-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.15.0-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.5.1-2?distro=sid
  affected_by_vulnerabilities:
    - VCID-u37h-3621-aaaj
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.5.1-2
  affected_by_vulnerabilities:
    - VCID-u37h-3621-aaaj
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.5.1-2%2Bdeb11u2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.5.1-2%2Bdeb11u2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.5.1-2%2Bdeb11u2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.8.2-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.8.2-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.8.2-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.8.2-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
