- purl: pkg:golang/github.com/docker/distribution@2.7.0-rc.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bnb5-p1qt-aaag
- purl: pkg:golang/github.com/docker/distribution@2.8.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-18tv-4u2q-aaah
- purl: pkg:golang/github.com/docker/distribution@2.8.2-beta.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-qwg4-wd4j-aaak
