- purl: pkg:npm/%40mittwald/kubernetes@1.0.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.10
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.11
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.12
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.16
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.17
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.18
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.19
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.2
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.20
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.21
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.22
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.3
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.4
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.5
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.6
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.7
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.8
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.0.0-beta.9
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.1.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.1.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.1.2
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.2.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.3.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.3.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.3.2
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.3.3
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.3.4
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.5.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.5.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.5.2
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.6.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@2.6.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.0.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.0.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.0.2
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.1.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.2.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.2.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.2.2
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.3.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.3.5
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.4.0
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.4.1
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.4.2
  affected_by_vulnerabilities:
    - VCID-nmyh-e56k-aaac
  fixing_vulnerabilities: []
- purl: pkg:npm/%40mittwald/kubernetes@3.5.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-nmyh-e56k-aaac
