- purl: pkg:alpm/archlinux/helm@3.5.1-1
  affected_by_vulnerabilities:
    - VCID-zv63-hf87-aaam
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/helm@3.5.2-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-zv63-hf87-aaam
- purl: pkg:alpm/archlinux/helm@3.6.0-1
  affected_by_vulnerabilities:
    - VCID-qve5-4atd-aaac
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/helm@3.6.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-qve5-4atd-aaac
