- purl: pkg:pypi/esphome@1.10.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.11.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.11.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.11.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.11.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.11.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.11.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.12.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.12.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.12.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.12.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.12.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.12.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.12.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0b5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0b6
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.0b7
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.13.6
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.0b5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.14.5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.15.3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b6
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b7
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.0b8
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.16.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.17.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.17.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.17.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.17.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.18.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.18.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.18.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.18.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.18.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0b5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0b6
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.0b7
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.19.4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.0b5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.0b6
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.20.4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.21.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.21.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@1.21.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.8.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.8.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.8.2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.0
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.0b1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.0b2
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.0b3
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.0b4
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.0b5
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.1
  affected_by_vulnerabilities:
    - VCID-ta6w-76wa-aaap
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2021.9.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-ta6w-76wa-aaap
- purl: pkg:pypi/esphome@2023.12.9
  affected_by_vulnerabilities:
    - VCID-14jm-kev2-aaar
    - VCID-3mq4-594w-aaae
    - VCID-awq2-xtya-aaac
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.2.0
  affected_by_vulnerabilities:
    - VCID-14jm-kev2-aaar
    - VCID-3mq4-594w-aaae
    - VCID-awq2-xtya-aaac
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.2.0b1
  affected_by_vulnerabilities:
    - VCID-14jm-kev2-aaar
    - VCID-3mq4-594w-aaae
    - VCID-awq2-xtya-aaac
  fixing_vulnerabilities:
    - VCID-14jm-kev2-aaar
- purl: pkg:pypi/esphome@2024.2.0b2
  affected_by_vulnerabilities:
    - VCID-14jm-kev2-aaar
    - VCID-3mq4-594w-aaae
    - VCID-awq2-xtya-aaac
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.2.0b3
  affected_by_vulnerabilities:
    - VCID-14jm-kev2-aaar
    - VCID-3mq4-594w-aaae
    - VCID-awq2-xtya-aaac
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.2.1
  affected_by_vulnerabilities:
    - VCID-3mq4-594w-aaae
    - VCID-awq2-xtya-aaac
  fixing_vulnerabilities:
    - VCID-14jm-kev2-aaar
- purl: pkg:pypi/esphome@2024.2.2
  affected_by_vulnerabilities:
    - VCID-3mq4-594w-aaae
  fixing_vulnerabilities:
    - VCID-awq2-xtya-aaac
- purl: pkg:pypi/esphome@2024.3.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-3mq4-594w-aaae
- purl: pkg:pypi/esphome@2024.3.0b1
  affected_by_vulnerabilities:
    - VCID-3mq4-594w-aaae
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.3.0b2
  affected_by_vulnerabilities:
    - VCID-3mq4-594w-aaae
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.3.0b3
  affected_by_vulnerabilities:
    - VCID-3mq4-594w-aaae
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.3.0b4
  affected_by_vulnerabilities:
    - VCID-3mq4-594w-aaae
  fixing_vulnerabilities: []
- purl: pkg:pypi/esphome@2024.3.0b5
  affected_by_vulnerabilities:
    - VCID-3mq4-594w-aaae
  fixing_vulnerabilities: []
