- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@0.15.1-1.gitba5da2c?arch=el7
  affected_by_vulnerabilities:
    - VCID-8g31-3v68-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@0.15.2-2.git98bc649?arch=el7
  affected_by_vulnerabilities:
    - VCID-3qb1-f6fw-aaad
    - VCID-sb3k-9d77-aaab
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.10.127-1.git.0.8ebe819?arch=el7
  affected_by_vulnerabilities:
    - VCID-3nc4-y8bt-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.10.14-1.git.892.af036cb?arch=el7
  affected_by_vulnerabilities:
    - VCID-kac9-8rqu-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.10.72-1.git.1060.64daa26?arch=el7
  affected_by_vulnerabilities:
    - VCID-e1j4-7hm1-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.117-1.git.1.dcee33f?arch=el7
  affected_by_vulnerabilities:
    - VCID-5wkx-e86u-aaap
    - VCID-pnup-jnde-aaaf
    - VCID-ukcz-wgqd-aaaq
    - VCID-ywt2-ng6w-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.154-1.git.1.bc9f224?arch=el7
  affected_by_vulnerabilities:
    - VCID-3gua-vux5-aaaq
    - VCID-6ypc-78mx-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.170-1.git.1.51473b7?arch=el7
  affected_by_vulnerabilities:
    - VCID-3maa-f8hf-aaar
    - VCID-6xwg-qb4m-aaab
    - VCID-any9-eahf-aaae
    - VCID-fc9g-cbgh-aaaq
    - VCID-j3r7-3uzr-aaag
    - VCID-tv97-anfg-aaam
    - VCID-w6e6-rtnb-aaac
    - VCID-xqsf-7315-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.219-1.git.1.7fa9674?arch=el7
  affected_by_vulnerabilities:
    - VCID-ysh4-ardx-aaah
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.248-1.git.1.32f87fc?arch=el7
  affected_by_vulnerabilities:
    - VCID-dmvz-1pz3-aaar
    - VCID-thj3-q935-aaah
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.374-1.git.1062.490d6d5?arch=el7
  affected_by_vulnerabilities:
    - VCID-7tef-cde1-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.51-1.git.1063.12dd8be?arch=el7
  affected_by_vulnerabilities:
    - VCID-1fjb-huub-aaar
    - VCID-3jde-awr2-aaap
    - VCID-4g16-xy22-aaaq
    - VCID-eyvp-37g8-aaag
    - VCID-kch3-k4m1-aaak
    - VCID-xkp1-2tqm-aaaf
    - VCID-z3b3-d8ux-aaas
    - VCID-zhtx-xjkr-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.82-1.git.1063.48444e8?arch=el7
  affected_by_vulnerabilities:
    - VCID-3req-4y1e-aaaf
    - VCID-5j7y-wd8f-aaaq
    - VCID-5uk8-gxpt-aaad
    - VCID-7264-zst7-aaaf
    - VCID-as9e-bjjf-aaam
    - VCID-e71d-zw6k-aaar
    - VCID-gsez-3sxq-aaak
    - VCID-khqb-36zq-aaaj
    - VCID-r6zg-c9a5-aaah
    - VCID-scxm-pvpw-aaap
    - VCID-sg4y-r86u-aaaf
    - VCID-twek-pn6u-aaap
    - VCID-v977-ccsj-aaaf
    - VCID-wwmq-456y-aaae
    - VCID-xcje-yrcw-aaaa
    - VCID-xxr3-nk7u-aaae
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.11.98-1.git.0.b02f11c?arch=el7
  affected_by_vulnerabilities:
    - VCID-3nc4-y8bt-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.9.101-1.git.1.8295224?arch=el7
  affected_by_vulnerabilities:
    - VCID-3gua-vux5-aaaq
    - VCID-6ypc-78mx-aaac
    - VCID-9uwj-8vtu-aaab
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.9.30-1.git.890.7ea5173?arch=el7
  affected_by_vulnerabilities:
    - VCID-auya-xges-aaan
    - VCID-v7bw-nwrc-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.9.31-1.git.890.a55de06?arch=el7
  affected_by_vulnerabilities:
    - VCID-hb1h-y42a-aaar
    - VCID-nkdd-9tw7-aaah
    - VCID-y8xq-xg5v-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.9.60-1.git.1063.df94c95?arch=el7
  affected_by_vulnerabilities:
    - VCID-z41h-v94f-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@3.9.74-1.git.0.2ab615c?arch=el7
  affected_by_vulnerabilities:
    - VCID-3nc4-y8bt-aaas
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@container-v3.11?arch=141-2
  affected_by_vulnerabilities:
    - VCID-qbz3-r843-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@container-v3.11?arch=146-2
  affected_by_vulnerabilities:
    - VCID-3vky-ea2p-aaap
    - VCID-6ap7-zs9m-aaag
    - VCID-hvu5-f1bj-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@container-v3.11?arch=82-3
  affected_by_vulnerabilities:
    - VCID-x3hr-wgvd-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@container-v3.11?arch=98-6
  affected_by_vulnerabilities:
    - VCID-r5q6-db7e-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@container-v4.1?arch=14-201908291507
  affected_by_vulnerabilities:
    - VCID-3gua-vux5-aaaq
    - VCID-6ypc-78mx-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@container-v4.2?arch=4-201911050122
  affected_by_vulnerabilities:
    - VCID-kq1v-8r3r-aaaf
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-prometheus-node_exporter@container-v4.3?arch=2-202002112006
  affected_by_vulnerabilities:
    - VCID-e1wn-9ha4-aaah
  fixing_vulnerabilities: []
