- purl: pkg:alpm/archlinux/prometheus@2.26.0-2
  affected_by_vulnerabilities:
    - VCID-8283-5hs3-aaar
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/prometheus@2.27.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
