- purl: pkg:pypi/github.com/grafana/grafana@0.0.1
  affected_by_vulnerabilities:
    - VCID-bde1-3cj5-aaan
  fixing_vulnerabilities: []
- purl: pkg:pypi/github.com/grafana/grafana@8.5.16
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bde1-3cj5-aaan
- purl: pkg:pypi/github.com/grafana/grafana@9.0.0
  affected_by_vulnerabilities:
    - VCID-bde1-3cj5-aaan
  fixing_vulnerabilities: []
- purl: pkg:pypi/github.com/grafana/grafana@9.2.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bde1-3cj5-aaan
