- purl: pkg:ebuild/app-emulation/docker@1.11.0
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-qu99-ca7p-aaac
- purl: pkg:ebuild/app-emulation/docker@19.03.12
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-wgvq-269b-aaaq
- purl: pkg:ebuild/app-emulation/docker@19.03.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cvtk-d332-aaaf
    - VCID-th43-scy8-aaab
- purl: pkg:ebuild/app-emulation/docker@20.10.3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cvtk-d332-aaaf
    - VCID-th43-scy8-aaab
