- pkg:rpm/redhat/tfm-rubygem-prometheus-client@0.7.1-1?arch=el7sat
- pkg:rpm/redhat/tfm-rubygem-prometheus-client@0.7.1-3?arch=el7sat
- pkg:rpm/redhat/tfm-rubygem-prometheus-client@1.0.0-1?arch=el7sat
