- pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-1.gitceca8c1?arch=el7
- pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-2.gitceca8c1?arch=el7
- pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-3.gitceca8c1?arch=el7
