- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-1.gitceca8c1?arch=el7
  affected_by_vulnerabilities:
    - VCID-8g31-3v68-aaan
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-2.gitceca8c1?arch=el7
  affected_by_vulnerabilities:
    - VCID-3qb1-f6fw-aaad
    - VCID-kac9-8rqu-aaaa
    - VCID-sb3k-9d77-aaab
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-3.gitceca8c1?arch=el7
  affected_by_vulnerabilities:
    - VCID-3gua-vux5-aaaq
    - VCID-6ypc-78mx-aaac
    - VCID-9uwj-8vtu-aaab
  fixing_vulnerabilities: []
