- purl: pkg:deb/debian/prometheus-alertmanager@0.15.3%2Bds-3?distro=trixie
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.15.3%2Bds-3
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.15.3%2Bds-3%2Bdeb10u1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.21.0%2Bds-4
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.21.0%2Bds-4?distro=trixie
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.25.0-1
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.25.0-1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.25.0%2Bds-1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.25.0%2Bds-1
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.26.0%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.26.0%2Bds-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.27.0%2Bds-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.27.0%2Bds-2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.27.0%2Bds-3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.27.0%2Bds-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.28.1%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.28.1%2Bds-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
- purl: pkg:deb/debian/prometheus-alertmanager@0.5.1%2Bds-7
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus-alertmanager@0.5.1%2Bds-7~bpo8%2B1
  affected_by_vulnerabilities:
    - VCID-q8qx-tpvu-aaae
  fixing_vulnerabilities: []
