- pkg:deb/debian/kubernetes@0?distro=trixie
- pkg:deb/debian/kubernetes@0?distro=sid
- pkg:deb/debian/kubernetes@1.17.4-1?distro=trixie
- pkg:deb/debian/kubernetes@1.17.4-1?distro=sid
- pkg:deb/debian/kubernetes@1.18.0-1?distro=trixie
- pkg:deb/debian/kubernetes@1.18.0-1?distro=sid
- pkg:deb/debian/kubernetes@1.18.2-1?distro=trixie
- pkg:deb/debian/kubernetes@1.18.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.18.5-1?distro=trixie
- pkg:deb/debian/kubernetes@1.18.5-1?distro=sid
- pkg:deb/debian/kubernetes@1.19.3-1?distro=trixie
- pkg:deb/debian/kubernetes@1.19.3-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.0-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.0-1?distro=trixie
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=trixie
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=trixie
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1%2Bdeb12u1?distro=trixie
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1%2Bdeb12u1
- pkg:deb/debian/kubernetes@1.31.4%2Bds-1?distro=sid
- pkg:deb/debian/kubernetes@1.31.4%2Bds-1?distro=trixie
- pkg:deb/debian/kubernetes@1.31.4%2Bds-2?distro=sid
- pkg:deb/debian/kubernetes@1.31.4%2Bds-2?distro=trixie
- pkg:deb/debian/kubernetes@1.31.4%2Bds-2
- pkg:deb/debian/kubernetes@1.32.3%2Bds-1
- pkg:deb/debian/kubernetes@1.32.3%2Bds-1?distro=trixie
- pkg:deb/debian/kubernetes@1.32.3%2Bds-2?distro=trixie
- pkg:deb/debian/kubernetes@1.32.3%2Bds-2
- pkg:deb/debian/kubernetes@1.33.4%2Bds-1?distro=trixie
- pkg:deb/debian/kubernetes@1.5.5%2Bdfsg-1?distro=trixie
- pkg:deb/debian/kubernetes@1.5.5%2Bdfsg-1?distro=sid
- pkg:deb/debian/kubernetes@1.7.16%2Bdfsg-1?distro=trixie
- pkg:deb/debian/kubernetes@1.7.16%2Bdfsg-1?distro=sid
