- purl: pkg:deb/debian/netplan.io@0.101-4?distro=trixie
  affected_by_vulnerabilities:
    - VCID-jndr-rujf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/netplan.io@0.101-4
  affected_by_vulnerabilities:
    - VCID-jndr-rujf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/netplan.io@0.106-2%2Bdeb12u1?distro=trixie
  affected_by_vulnerabilities:
    - VCID-jndr-rujf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/netplan.io@0.106-2%2Bdeb12u1
  affected_by_vulnerabilities:
    - VCID-jndr-rujf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/netplan.io@1.0.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.0.1-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.0.1-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.0-3?distro=trixie
  affected_by_vulnerabilities:
    - VCID-jndr-rujf-aaaf
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/netplan.io@1.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.1-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-4?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-5?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-6?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-7?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
- purl: pkg:deb/debian/netplan.io@1.1.2-8?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jndr-rujf-aaaf
