- pkg:rpm/redhat/cloud-init@0.7.5-1?arch=el6
- pkg:rpm/redhat/cloud-init@18.2-1.el7_6?arch=2
- pkg:rpm/redhat/cloud-init@18.5-12.el8_2?arch=10
- pkg:rpm/redhat/cloud-init@18.5-12.el8_2?arch=3
- pkg:rpm/redhat/cloud-init@18.5-1.el8?arch=4
- pkg:rpm/redhat/cloud-init@18.5-7.el8_1?arch=6
- pkg:rpm/redhat/cloud-init@19.4-11?arch=el8
- pkg:rpm/redhat/cloud-init@19.4-1.el8?arch=7
- pkg:rpm/redhat/cloud-init@19.4-7?arch=el7
- pkg:rpm/redhat/cloud-init@20.3-10.el8_4?arch=5
- pkg:rpm/redhat/cloud-init@23.1.1-10?arch=el8
- pkg:rpm/redhat/cloud-init@23.1.1-11?arch=el9
