- pkg:rpm/redhat/cloud-init@0.7.5-1?arch=el6
- pkg:rpm/redhat/cloud-init@18.2-1.el7_6?arch=2
- pkg:rpm/redhat/cloud-init@18.5-12.el8_2?arch=10
- pkg:rpm/redhat/cloud-init@18.5-12.el8_2?arch=3
- pkg:rpm/redhat/cloud-init@18.5-1.el8?arch=4
- pkg:rpm/redhat/cloud-init@18.5-7.el8_1?arch=6
- pkg:rpm/redhat/cloud-init@19.4-11?arch=el8
- pkg:rpm/redhat/cloud-init@19.4-1.el8?arch=7
- pkg:rpm/redhat/cloud-init@19.4-7?arch=el7
- pkg:rpm/redhat/cloud-init@20.3-10.el8_4?arch=5
- pkg:rpm/redhat/cloud-init@21.1-15.el8_6?arch=4
- pkg:rpm/redhat/cloud-init@21.1-19.el9_0?arch=7
- pkg:rpm/redhat/cloud-init@22.1-10.el9_2?arch=1
- pkg:rpm/redhat/cloud-init@22.1-8.el8_8?arch=2
- pkg:rpm/redhat/cloud-init@23.1.1-10?arch=el8
- pkg:rpm/redhat/cloud-init@23.1.1-11?arch=el9
- pkg:rpm/redhat/cloud-init@23.4-7.el8_10?arch=10
- pkg:rpm/redhat/cloud-init@23.4-7.el9_4?arch=13
- pkg:rpm/redhat/cloud-init@24.4-3.el10_0?arch=2
- pkg:rpm/redhat/cloud-init@24.4-4.el9_6?arch=3
