- purl: pkg:rpm/redhat/cloud-init@0.7.5-1?arch=el6
  affected_by_vulnerabilities:
    - VCID-us5b-bv9a-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@18.2-1.el7_6?arch=2
  affected_by_vulnerabilities:
    - VCID-rgk6-gc76-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@18.5-12.el8_2?arch=10
  affected_by_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@18.5-12.el8_2?arch=3
  affected_by_vulnerabilities:
    - VCID-jrtj-mr5x-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@18.5-1.el8?arch=4
  affected_by_vulnerabilities:
    - VCID-rgk6-gc76-aaar
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@18.5-7.el8_1?arch=6
  affected_by_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@19.4-11?arch=el8
  affected_by_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@19.4-1.el8?arch=7
  affected_by_vulnerabilities:
    - VCID-jrtj-mr5x-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@19.4-7?arch=el7
  affected_by_vulnerabilities:
    - VCID-5sez-wgc8-aaaq
    - VCID-bjwp-wq7y-aaad
    - VCID-jrtj-mr5x-aaak
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@20.3-10.el8_4?arch=5
  affected_by_vulnerabilities:
    - VCID-nphr-p5x9-aaaj
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@21.1-15.el8_6?arch=4
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@21.1-19.el9_0?arch=7
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@22.1-10.el9_2?arch=1
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@22.1-8.el8_8?arch=2
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@23.1.1-10?arch=el8
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@23.1.1-11?arch=el9
  affected_by_vulnerabilities:
    - VCID-mkrm-q7yw-aaaq
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@23.4-7.el8_10?arch=10
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@23.4-7.el9_4?arch=13
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@24.4-3.el10_0?arch=2
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/cloud-init@24.4-4.el9_6?arch=3
  affected_by_vulnerabilities:
    - VCID-b9jd-wm14-kkb5
  fixing_vulnerabilities: []
