- pkg:rpm/redhat/httpd-configmap-generator@0.2.1-1?arch=el7cf
- pkg:rpm/redhat/httpd-configmap-generator@0.2.1-2?arch=el7cf
- pkg:rpm/redhat/httpd-configmap-generator@0.2.2-1.1?arch=el7cf
- pkg:rpm/redhat/httpd-configmap-generator@0.2.2-1.2?arch=el7cf
- pkg:rpm/redhat/httpd-configmap-generator@0.2.2-2?arch=el7cf
