- purl: pkg:rpm/redhat/httpd-configmap-generator@0.2.1-1?arch=el7cf
  affected_by_vulnerabilities:
    - VCID-qez8-dgmj-aaak
    - VCID-xmx5-a45m-aaap
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/httpd-configmap-generator@0.2.1-2?arch=el7cf
  affected_by_vulnerabilities:
    - VCID-4tkc-jaj1-aaam
    - VCID-m6ju-nbce-aaag
    - VCID-zx4q-ry22-aaam
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/httpd-configmap-generator@0.2.2-1.1?arch=el7cf
  affected_by_vulnerabilities:
    - VCID-vpzy-gc78-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/httpd-configmap-generator@0.2.2-1.2?arch=el7cf
  affected_by_vulnerabilities:
    - VCID-284w-w9ec-aaaa
    - VCID-c6cj-4u8q-aaap
    - VCID-gmgw-23h9-aaap
    - VCID-w4q3-kj53-aaaa
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/httpd-configmap-generator@0.2.2-2?arch=el7cf
  affected_by_vulnerabilities:
    - VCID-22mr-wwfc-aaab
    - VCID-pjrb-txh7-aaak
    - VCID-r4sj-m8p3-aaaq
    - VCID-xzna-6eg3-aaag
  fixing_vulnerabilities: []
