- purl: pkg:alpm/archlinux/traefik@2.4.13-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-bbuw-5mse-aaar
- purl: pkg:alpm/archlinux/traefik@2.4.2-1
  affected_by_vulnerabilities:
    - VCID-bffr-sm76-aaan
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/traefik@2.4.8-1
  affected_by_vulnerabilities:
    - VCID-bbuw-5mse-aaar
  fixing_vulnerabilities:
    - VCID-bffr-sm76-aaan
