- pkg:maven/org.jenkins-ci.plugins/ansible@0.8
- pkg:maven/org.jenkins-ci.plugins/ansible@1.0
- pkg:maven/org.jenkins-ci.plugins/ansible@1.1
- pkg:maven/org.jenkins-ci.plugins/ansible@204.v8191fd551eb_f
- pkg:maven/org.jenkins-ci.plugins/ansible@205.v4cb
