- purl: pkg:maven/org.jenkins-ci.plugins/ansible@0.8
  affected_by_vulnerabilities:
    - VCID-9np7-79fu-aaan
  fixing_vulnerabilities: []
- purl: pkg:maven/org.jenkins-ci.plugins/ansible@1.0
  affected_by_vulnerabilities:
    - VCID-2ehj-kk65-aaaj
  fixing_vulnerabilities:
    - VCID-9np7-79fu-aaan
- purl: pkg:maven/org.jenkins-ci.plugins/ansible@1.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-2ehj-kk65-aaaj
- purl: pkg:maven/org.jenkins-ci.plugins/ansible@204.v8191fd551eb_f
  affected_by_vulnerabilities:
    - VCID-xg2d-bndd-aaaj
  fixing_vulnerabilities: []
- purl: pkg:maven/org.jenkins-ci.plugins/ansible@205.v4cb
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-sszz-2nyz-aaaq
    - VCID-xg2d-bndd-aaaj
