- pkg:rpm/redhat/python-ironic-prometheus-exporter@0.0.1-0.20190712090404.f7e9344?arch=el8ost
- pkg:rpm/redhat/python-ironic-prometheus-exporter@3.1.1-0.20220324125409.db1a824?arch=el8
- pkg:rpm/redhat/python-ironic-prometheus-exporter@3.1.1-0.20221003235527.eb27243?arch=el9
- pkg:rpm/redhat/python-ironic-prometheus-exporter@4.1.1-0.20230614150617.7b35627?arch=el9
