- purl: pkg:rpm/redhat/python-ironic-prometheus-exporter@0.0.1-0.20190712090404.f7e9344?arch=el8ost
  affected_by_vulnerabilities:
    - VCID-2cqt-v8wb-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/python-ironic-prometheus-exporter@3.1.1-0.20220324125409.db1a824?arch=el8
  affected_by_vulnerabilities:
    - VCID-7jyw-7cbe-aaag
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/python-ironic-prometheus-exporter@3.1.1-0.20221003235527.eb27243?arch=el9
  affected_by_vulnerabilities:
    - VCID-pn75-hsb4-aaac
  fixing_vulnerabilities: []
- purl: pkg:rpm/redhat/python-ironic-prometheus-exporter@4.1.1-0.20230614150617.7b35627?arch=el9
  affected_by_vulnerabilities:
    - VCID-aafc-9fsp-aaam
    - VCID-q2tw-bu8w-aaah
  fixing_vulnerabilities: []
