- purl: pkg:alpm/archlinux/docker@1:1.12.5-1
  affected_by_vulnerabilities:
    - VCID-funr-5s9t-aaak
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/docker@1:1.12.6-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-funr-5s9t-aaak
- purl: pkg:alpm/archlinux/docker@1:18.09.1-2
  affected_by_vulnerabilities:
    - VCID-rtmc-4r84-aaas
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/docker@1:18.09.2-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-rtmc-4r84-aaas
- purl: pkg:alpm/archlinux/docker@1:18.09.6-1
  affected_by_vulnerabilities:
    - VCID-1a7v-a4dt-aaam
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/docker@1:18.09.7-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-1a7v-a4dt-aaam
- purl: pkg:alpm/archlinux/docker@1:20.10.10-1
  affected_by_vulnerabilities:
    - VCID-vsk2-k3mh-aaah
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/docker@1:20.10.11-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-vsk2-k3mh-aaah
- purl: pkg:alpm/archlinux/docker@1:20.10.2-4
  affected_by_vulnerabilities:
    - VCID-cvtk-d332-aaaf
    - VCID-th43-scy8-aaab
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/docker@1:20.10.3-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-cvtk-d332-aaaf
    - VCID-th43-scy8-aaab
- purl: pkg:alpm/archlinux/docker@1:20.10.8-1
  affected_by_vulnerabilities:
    - VCID-98m9-ft46-aaah
    - VCID-fckq-6rf5-aaaf
    - VCID-qgrb-pu21-aaab
  fixing_vulnerabilities: []
- purl: pkg:alpm/archlinux/docker@1:20.10.9-1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-98m9-ft46-aaah
    - VCID-fckq-6rf5-aaaf
    - VCID-qgrb-pu21-aaab
