- purl: pkg:deb/debian/prometheus@0?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@0?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
- purl: pkg:deb/debian/prometheus@0?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
- purl: pkg:deb/debian/prometheus@1.5.2%2Bds-2?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@1.5.2%2Bds-2
  affected_by_vulnerabilities:
    - VCID-r6zg-c9a5-aaah
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus@1.5.2%2Bds-2~bpo8%2B1
  affected_by_vulnerabilities:
    - VCID-r6zg-c9a5-aaah
  fixing_vulnerabilities: []
- purl: pkg:deb/debian/prometheus@2.24.1%2Bds-1?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.24.1%2Bds-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.24.1%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.33.5%2Bds1-2?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.33.5%2Bds1-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.33.5%2Bds1-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.33.5%2Bds1-4?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.39.1%2Bds1-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.39.1%2Bds1-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.40.0%2Bds-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.40.1%2Bds-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.40.2%2Bds-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.40.3%2Bds-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.40.5%2Bds-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.41.0%2Bds-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.41.0%2Bds-2?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.42.0%2Bds-5?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.42.0%2Bds-5?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.42.0%2Bds-6?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.43.1%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.44.0%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.0%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.0%2Bds-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.0%2Bds-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.0%2Bds-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.1%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.1%2Bds-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.1%2Bds-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.3%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.4%2Bds-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.5%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-2?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-4?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-5?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-7?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-8?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.45.6%2Bds-9?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.53.3%2Bds1-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.7.1%2Bds-1?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.7.1%2Bds-1?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.7.1%2Bds-1?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.7.1%2Bds-3?distro=stretch
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.7.1%2Bds-3?distro=sid
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.7.1%2Bds-3?distro=trixie
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8283-5hs3-aaar
    - VCID-r6zg-c9a5-aaah
- purl: pkg:deb/debian/prometheus@2.7.1%2Bds-3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-r6zg-c9a5-aaah
