- purl: pkg:golang/github.com/prometheus/exporter-toolkit@0.7.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
- purl: pkg:golang/github.com/prometheus/exporter-toolkit@0.8.2
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-u37h-3621-aaaj
