- purl: pkg:maven/org.jenkins-ci.plugins/deploy@1.12
  affected_by_vulnerabilities:
    - VCID-d8gy-ap7k-aaab
  fixing_vulnerabilities: []
- purl: pkg:maven/org.jenkins-ci.plugins/deploy@1.13
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-d8gy-ap7k-aaab
