- purl: pkg:golang/github.com/grafana/grafana/pkg/web@7.5.15
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8fm5-p9ys-aaag
- purl: pkg:golang/github.com/grafana/grafana/pkg/web@8.3.5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-8fm5-p9ys-aaag
