- purl: pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.17.0
  affected_by_vulnerabilities:
    - VCID-48mb-hd2h-aaae
  fixing_vulnerabilities: []
- purl: pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.17.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-48mb-hd2h-aaae
