- purl: pkg:golang/github.com/grafana/alloy@1.3.4
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jzfw-14c3-d7cb
- purl: pkg:golang/github.com/grafana/alloy@1.4.1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-jzfw-14c3-d7cb
