- pkg:ebuild/app-admin/ansible@1.6.8
- pkg:ebuild/app-admin/ansible@2.0.2.0-r1
- pkg:ebuild/app-admin/ansible@2.1.4.0_rc3
- pkg:ebuild/app-admin/ansible@2.2.1.0_rc5
- pkg:ebuild/app-admin/ansible@2.9.7
