- purl: pkg:ebuild/app-admin/ansible@1.6.8
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-4cgp-6ar8-aaab
    - VCID-pze9-prz5-aaap
    - VCID-qvr1-4hve-aaaa
    - VCID-zxh4-zrbz-aaaf
- purl: pkg:ebuild/app-admin/ansible@2.0.2.0-r1
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-sxuh-5a7s-aaap
- purl: pkg:ebuild/app-admin/ansible@2.1.4.0_rc3
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-scu2-mz1c-aaan
- purl: pkg:ebuild/app-admin/ansible@2.2.1.0_rc5
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-scu2-mz1c-aaan
- purl: pkg:ebuild/app-admin/ansible@2.9.7
  affected_by_vulnerabilities: []
  fixing_vulnerabilities:
    - VCID-9xje-8wsd-aaam
    - VCID-dp5x-5n9f-aaah
    - VCID-mrhc-f3xq-aaaa
    - VCID-n3vw-pvhw-aaaf
    - VCID-na52-qryf-aaae
    - VCID-nxj9-2mgr-aaak
    - VCID-sxyq-umyp-aaar
    - VCID-t2tw-36t9-aaab
    - VCID-x97v-vpy8-aaan
